-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th1 03, 2019 lúc 05:10 PM
-- Phiên bản máy phục vụ: 10.1.36-MariaDB
-- Phiên bản PHP: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `project`
--
CREATE DATABASE IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `project`;
-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `comment`
--

CREATE TABLE `comment` (
  `id` int(10) UNSIGNED NOT NULL,
  `idUser` int(10) UNSIGNED NOT NULL,
  `idCongThuc` int(10) UNSIGNED NOT NULL,
  `NoiDung` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `congthuc`
--

CREATE TABLE `congthuc` (
  `id` int(10) UNSIGNED NOT NULL,
  `TieuDe` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
  `TieuDeKhongDau` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
  `NoiDung` longtext CHARACTER SET utf8mb4 NOT NULL,
  `Hinh` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
  `NoiBat` int(11) NOT NULL,
  `SoLuotXem` int(11) NOT NULL,
  `idLoaiMon` int(10) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `congthuc`
--

INSERT INTO `congthuc` (`id`, `TieuDe`, `TieuDeKhongDau`, `NoiDung`, `Hinh`, `NoiBat`, `SoLuotXem`, `idLoaiMon`, `created_at`, `updated_at`) VALUES
(1, 'Bánh bao nhân thịt', 'banh-bao-nhan-thit', 'Bước 1: Cho 400g bột mì, 4g men nở vào thố trộn bột, thêm từ từ nước rồi khởi động máy. Lượng nước sao vừa đủ bột thành khối đồng nhất. Tránh rót 1 lúc nhiều nước bột sẽ nhão nhé! Sau đó bọc màng thực phẩm lại, đem ủ bột nở gấp đôi. Bột sau khi ở chia đều thành những phần đều nhau. <br>\r\nBước 2: Băm nhỏ cần tây, hành lá và gừng rồi trộn với thịt heo bằm cùng hỗn hợp gia vị nêm gồm: 1/2 muỗng cà phê muối, 1 viên chao, 2 muỗng cà phê hạt nêm, 15ml nước tương, 10g dầu hào, 15ml dầu mè và trộn theo một hướng. <br>\r\nBước 3: Vê tròn rồi cán dẹp các viên bột. Múc 1 muỗng nhân thịt heo bằm cho vào rồi gói kín lại cho đẹp mắt nhé! <br>\r\nBước 4: Cho 40ml dầu ăn vào chảo. Đổ thêm vào khoảng nửa chén nước. Đậu nắp vung lại, chiên bánh ở lửa nhỏ cho bánh nở xốp mềm. Đáy bánh cháy xém vàng cam là được nhé! <br>\r\nBước 5: Trông những chiếc bánh xinh xắn thế này thì hỏi ai không mê mẩn cho được. Bánh bao nhân thịt băm chiên áp chảo giúp bạn trải nghiệm hương vị béo bùi của thịt. Vỏ bánh xốp mềm nóng hổi, sẵn sàng làm ấm lòng cho bạn vào bữa sáng. <br>', 'banh_bao_nhan_thit.jpg', 0, 0, 1, '2019-01-01 06:47:33', '2019-01-01 06:47:33'),
(2, 'Bánh chưng', 'banh-chung', 'Bước 1: Nếp Bắc vo sạch, ngâm nước trong 4 giờ, vớt ra để ráo, trộn nếp với 3 muỗng cà phê muối. Đậu xanh không vỏ rửa sạch, ngâm 1 với nước giờ rồi đem đi hấp chín, xay nhuyễn, trộn với 1.5 muỗng cà phê muối, vắt thành 2 viên. Lá chuối lau sạch. <br>\r\nBước 2: Thịt ba chỉ rửa sạch để ráo, cắt thịt thành từng miếng có bản rộng và dày khoảng 1cm. Ướp thịt với 1 muỗng cà phê muối, 2 muỗng cà phê tiêu rồi để riêng. Vậy là bạn đã có nếp, đậu xanh, thịt ba chỉ, lá chuối để gói bánh, à nhớ chuẩn bị thêm 1 cuộn chỉ hoặc lạt để buộc bánh nữa nhé. <br>\r\nBước 3: Lá chuối bỏ sống lá, gốc và đầu lá, gấp đôi theo chiều dọc, rồi theo chiều ngang. Xếp 2 sợi chỉ thành hình chữ thập, cho khuôn lên. Đặt lá 1 bên cạnh khuôn, mở ra theo chiều dọc, cho mép lá kia sát cạnh khuôn cùng bên để tạo góc vuông. <br>\r\nBước 4: Phần mép lá nằm phía dưới thì bẻ mép 2 cạnh lá, tạo hình tam giác dưới đáy. Lấy 1 lá khác lặp lại như vậy với góc đối diện, thêm 2 lá cho vào hai góc còn lại (không bẻ mép lá thành hình tam giác mà mở ra để tạo đáy). <br>\r\nBước 5: Lót thêm 1 lá vào khuôn, cho nếp, đậu, thịt ba chỉlên, trên cùng là nếp, rồi dùng 1 lá đậy lên. Xếp gọn các mép lá thừa, xếp 2 bên rồi xếp lại lần nữa. <br>\r\nBước 6: Buộc sơ dây chỉ/lạt có sẵn để cố định bánh. Sau đó lần lượt buộc thêm 2 dây ngang, 1 dây dọc (có thể thêm 3 dây ngang, 2 dây dọc cũng được). Có thể cắt bỏ bớt dây thừa cho bánh gọn đẹp hơn. <br>\r\nBước 7: Lót cọng lá chuối vào đáy nồi. Xếp bánh chưng vào, đổ ngập nước. Đun lửa lớn cho sôi rồi để lửa trung bình. Canh châm nước luôn ngập bánh, luộc khoảng 10 giờ là chín. Vớt bánh ra, rửa sạch với nước lạnh, dùng vật nặng đè lên khoảng 2 giờ, treo nơi thoáng mát. <br>\r\nBước 8: Khi thưởng thức, bạn tháo bánh chưng ra. dùng chính đạon chỉ/lạt để quấn quanh bánh chưng và cắt thành các miếng vừa ăn, nếu không biết cách dùng chỉ, bạn có thể dùng sao, tuy nhiên sẽ rất dính dao nha. Chúc bạn có một cái Tết đầm ấm bên gia đình. <br>\r\n', 'banh_chung.jpg', 0, 0, 7, '2019-01-01 07:07:52', '2019-01-01 07:07:52'),
(3, 'Bánh flan caramel', 'banh-flan-caramel', 'Bước 1: Phần caramel: Bật lò nướng trước ở 150 độ C. Cho 140g đường vào nồi với 60ml nước, khuấy đều. Đặt nồi lên bếp, nấu sôi nhưng không khuấy bạn nhé. Khi thấy nước đường dần chuyển sang màu vàng thì cầm nồi lên nhẹ nhàng xoay đến khi có màu mật ong thì tắt bếp. Sau đó tiếp tục xoay khoảng 15 - 20 giây, có màu hổ phách đỏ, cho vào 2 muỗng canh nước ấm và khuấy nhẹ tầm 10 phút. Khi đã thu được caramel, bạn đổ vào khuôn bánh kích thước 12x20cm. <br>\r\nBước 2: Phần flan: Cho 2 quả trứng cùng 5 lòng đỏ vào âu, đánh đến khi trứng hòa quyện đều với nhau. Sau đó cho 1 hộp sữa đặc có đường, 1 hộp sữa đặc không đường, 125ml sữa tươi nguyên kem, 2 muỗng tinh chất vani, 1 muỗng rượu, 1/2 muỗng muối, dùng phới lồng trộn cho hỗn hợp hòa quyện vào nhau. Đổ trứng qua rây lược lại rồi đổ vào khuôn caramel khi nãy. Đặt khuôn vào khay nướng, chế nước vào vừa đủ rồi đặt khay flan vào lò nướng 70 - 90 phút là bánh chín. Lấy ra để nguội như vậy 1 tiếng. <br>\r\nBước 3: Sau đó, bọc khuôn bánh flan bằng màng bọc thực phẩm và cho vào tủ lạnh qua đêm để flan đông lại, chắc chắn. Lấy flan ra, nhẹ nhàng dùng dao cắt xung quanh các cạnh khuôn để tách flan. Cẩn thận úp ngược khuôn flan xuống dĩa và bánh sẽ trượt ra là được nha. <br>\r\nBước 4: Vậy là chúng ta đã làm xong chiếc Bánh flan caramel mềm mịn, thơm lừng kèm vị béo của trứng cực kì hấp dẫn luôn đấy. Bạn hãy thử làm ngay công thức này vào cuối tuần cho cả nhà tráng miệng nha. <br>', 'banh_flan_caramel.jpg', 0, 0, 2, '2019-01-01 07:25:34', '2019-01-01 07:25:34'),
(4, 'Bánh mì hấp', 'banh-mi-hap', 'Bước 1: Nấm mèo ngâm với nước ấm cho nở, thái hạt lượu. Củ cà rốt gọt vỏ, rửa sạch, thái hạt lựu như nấm mèo. Hành lá thái nhuyễn. Ướp thịt với ¼ muỗng cà phê bột ngọt, 1 muỗng cà phê bột nêm, 1 muỗng canh nước mắm, 1/3 hành lá, rồi trộn đều. Rau thơm nhặt bỏ lá sâu, xà lách bỏ gốc rồi rửa rau thật sạch, để ráo. Tỏi bóc vỏ, băm nhuyễn. <br>\r\nBước 2: Đun nóng dầu ăn, cho vào một ít tỏi, phi thơm. Sau đó cho thịt vào xào chín. Tiếp theo cho cà rốt và nấm mèo vào xào chung. Nêm vào ½ muỗng cà phê muối, đảo đều. Xào đến khi cà rốt mềm thì cho hết số hành lá còn lại vào. Đảo thêm vài lần nữa cho hành chín. <br>\r\nBước 3: Pha nước mắm: cho 6 muỗng canh nước mắm, 2 muỗng canh đường, 3 muỗng nước sôi để nguội, nước cốt 1 quả chanh vào tô. Khuấy đều cho đường tan hết. Cho tỏi băm, ớt băm vào sau cùng để ớt và tỏi nổi lên cho đẹp nhé.Bánh mì cắt làm 4. Đun sôi một nồi nước, cho bánh mì vào hấp 5 phút là được. <br>\r\nBước 4: Khi ăn cho bánh mì mới vừa hấp ra dĩa, múc thịt xào lên trên bánh mì. Gói bánh mì bằng một lá xà lách kèm với rau thơm bên trong, chấm với nước mắm chua ngọt. Bánh mì mới hấp còn rất mềm thơm, thêm nhân thịt đậm đà rất hấp dẫn. <br>', 'banh_mi_hap.jpg', 0, 0, 2, '2019-01-01 07:25:34', '2019-01-01 07:25:34'),
(5, 'Bánh Paparotti', 'banh-paparotti', 'Bước 1:Cho sữa vào một cái tô, thêm men vào khuấy nhẹ, để nghỉ 3 phút cho men nở phồng như gạch cua. Cho bột mì, sữa bột, men nở, đường, 1 quả trứng gà, sữa không đường, muối vào tô. Trộn nhào khoảng 20 phút. Sau khi nhào bạn sẽ được một viên bột tròn, dai, mịn. <br>\r\nBước 2: Cho 35gr bơ vào tô trộn lớn, quét đều quanh tô. Cho khối bột vào tô. Bọc kín bằng màng bọc thực phẩm, để trong lò nướng cho kín hơi khoảng 1 giờ. Sau 1 giờ bột đã nở hơn gấp đôi. Ấn bột loại bỏ phần khí trong bột ủ, nhồi cùng bơ đến khi bột thành một khối thì để bột nghỉ 15 phút. <br>\r\nBước 3: Lót sẵn giấy nến trên khay nướng. Chia bột thành những viên bằng nhau, bỏ mỗi phần phô mai vào chính giữa bột . Vê tròn bột xung quanh phô mai. Lần lượt làm hết phần bột còn lại, bạn lưu ý khi đã tạo hình xong thì dùng màng bọc thực phẩm che lại giúp cho bột không bị khô. Ủ bột thêm 1 giờ nữa tới khi bánh nở gấp đôi. <br>\r\nBước 4: Làm phần phủ bánh: Cho nước nóng hòa tan với 2 gói cà phê rồi để riêng. Cho 35gr bơ và 35gr đường bột vào tô trộn, đánh tới khi nhuyễn mịn thì thêm 1 quả trứng cùng với sữa bột và bột mì vào. Đánh tới khi hỗn hợp mịn, nhuyễn. Cho cà phê hòa tan vào. Cho phần phủ bánh vào túi bắt bông kem, để trong ngăn mát tủ lạnh. <br>\r\nBước 5: Đợi bánh đến khi bánh nở đủ thì cắt 1 góc nhỏ trên đầu túi bắt bông kem. Bóp phần phủ này lên mặt bánh theo hình xoắn ốc, khoảng 1/2 bánh. Bật lò nướng nóng trước khoảng 10 phút với nhiệt 180ºC, cho bánh vào lò nướng trong vòng 15 - 20 phút. Sau 5 phút đưa vào lò, phần phủ bánh sẽ chảy xuống phủ toàn bộ mặt bánh và dậy mùi cà phê thơm phức. Sau khi đã hết thời gian nướng, bánh nở tròn đều, bạn lấy bánh ra khỏi lò. <br>\r\nBước 6: Đợi bánh đến khi bánh nở đủ thì cắt 1 góc nhỏ trên đầu túi bắt bông kem. Bóp phần phủ này lên mặt bánh theo hình xoắn ốc, khoảng 1/2 bánh. Bật lò nướng nóng trước khoảng 10 phút với nhiệt 180ºC, cho bánh vào lò nướng trong vòng 15 - 20 phút. Sau 5 phút đưa vào lò, phần phủ bánh sẽ chảy xuống phủ toàn bộ mặt bánh và dậy mùi cà phê thơm phức. Sau khi đã hết thời gian nướng, bánh nở tròn đều, bạn lấy bánh ra khỏi lò. <br>', 'banh_paparotti.jpg', 0, 0, 1, '2019-01-01 07:25:34', '2019-01-01 07:25:34'),
(6, 'Bánh su kem sữa trứng', 'banh-su-kem-sua-trung', 'Bước 1: Chuẩn bị nguyên liệu, cân sẵn khối lượng trước cho tiết kiệm thời gian. Đập trứng cho vào tô. <br>\r\nBước 2: Cách làm kem sữa trứng: Lòng đỏ trứng gà, đường, muối, bột khoai tây, bột đường vanilla & sữa tươi đổ tất cả vào chung trong thau nhựa lớn, dùng cây phới khuấy tất cả tan đều. Rồi dùng rây lọc tất cả hỗn hợp vào trong 1 cái nồi, để lược bỏ những viên bột bị vón lợn cợn. <br>\r\nBước 3: Tiếp theo, bỏ bơ vào chung rồi bắt nồi lên bếp nấu từ từ ở lửa trung bình, đồng thời dùng cây phới khuấy hỗn hợp sữa liên tục đều tay để không bị dính dưới đáy nồi, khi cảm nhận sữa hỗn hợp hơi sôi lụp bụp và bắt đầu đặc lại thì hạ lửa nhỏ hơn, tiếp tục khuấy liên tục để sữa không bị cháy. <br>\r\nBước 4: Khi thấy nồi kem sánh đặc sệt lại thì bắt nồi ra khỏi bếp để nguội, sau đó cho nồi kem sữa trứng vào trong tủ lạnh ngăn mát khoảng 4 - 5 giờ. <br>\r\nBước 5: Cách làm vỏ bánh: Nước, bơ và muối bỏ vào nồi rồi bắc lên bếp nấu cho bơ tan ra, sau đó bắt nồi ra khỏi bếp. Tiếp theo đổ bột mì vào nồi nước bơ khi còn đang nóng, rồi dùng cây muỗng gỗ quấy trộn theo vòng tròn đều tay, cho đến khi thấy bột quyện dẻo thành khối và không dính vào thành nồi là được. <br>\r\nBước 6: Đập mỗi lần 2 quả trứng vào nồi bột hỗn hợp, tiếp tục quấy trộn đều tay, khi thấy trứng đã quyện đều với bột thì đập tiếp 2 qủa trứng vào, cứ làm như vậy cho đến khi hết 8 quả trứng. <br>\r\nBước 7: Đặt giấy nến nướng bánh lên khay nướng, rồi nặn/bắt thành kiểu xoắn tròn khoảng 3 vòng (nhìn hình chỉ dẫn), cứ nặn/bắt như vậy cho đến khi hết số lượng bột hỗn hợp. Lò nướng mở 200 độ trước 10 phút, sau đó bỏ khay bánh vào nướng thì hạ lò xuống 175 độ. <br>\r\nBước 8: Dùng ít giấy báo xếp thành 1 độ dày tương đối rồi để giữa kẽ của nắp lò nướng (nhìn như hình chỉ dẫn), để tạo 1 lớp hở ở nắp lò cho hơi nóng từ lò nướng thoát ra (cách làm này giúp bánh sau khi nướng xong lấy ra khỏi lò, bánh luôn giữ hình dạng đứng nở phồng chứ ko bị xẹp). Rồi nướng bánh từ khoảng 25 - 30 phút tùy theo nhiệt độ lò nướng, hoặc khi thấy bánh ngã màu hơi vàng, thì lấy giấy báo ra rồi đậy nắp lò kín lại và nướng thêm 5 phút nữa, lấy bánh ra ngoài để cho thật nguội. <br>\r\nBước 9: Bánh nướng sau khi để nguội, dùng dao có răng cưa khứa/rạch 1 đường dài khoảng 1/3 bên hông của thành bánh (nhìn hình chỉ dẫn). Kem sữa tươi bỏ vào túi nylon nặn/bắt bông kem, rồi từ từ bóp kem vào trong bụng bánh, cứ làm như vậy cho đến khi hết số lượng bánh. <br>\r\nBước 10: Cho thêm một ít bột rắt lên mặt bánh cho đẹp. Thế là đã hoàn thành các bước làm bánh su kem sữa trứng tại nhà rồi. Chúc cả nhà thành công nha! <br>\r\n\r\n', 'banh_su_kem_sua_trung.jpg', 0, 0, 7, '2019-01-01 07:58:31', '2019-01-01 07:58:31'),
(7, 'Bánh tép chiên giòn', 'banh-tep-chien-gion', 'Bước 1: Tép đồng cắt đầu, rửa sạch. Bông điên điển chọn bông còn tươi vàng, rửa sạch. Hành tây cắt lát mỏng. Chuẩn bị tô lớn, cho vào 200gr tép, 200gr bông điên điển, 10gr hành tây, 1 quả trứng gà cùng các gia vị 1 muỗng cà phê hạt nêm, 1 muỗng cà phê tiêu, 2 muỗng cà phê nước mắm và 100gr bột chiên giòn. Trộn đều để hỗn hợp được hòa quyện với nhau. <br>\r\nBước 2: Bắc chảo lên bếp cho dầu vào đun sôi (lượng dầu phải ngập miếng bột chiên). Dùng muỗng múc từng miếng bột có lẫn tép cho vào chảo chiên vàng, khi vàng giòn 2 mặt thì vớt ra giấy thấm dầu để ráo. <br>\r\nBước 3: Bánh tép chiên giòn là món ăn dân dã nhung cực kỳ ngon miệng, được người lớn và trẻ nhỏ đều yêu thích. Miếng bánh tép giòn rụm nhai rôm rốp, cuốn bánh tráng, rau sống, chấm cùng nước chấm chua ngọt thì ngon hết biết! <br>', 'banh_tep_chien_gion.jpg', 0, 0, 7, '2019-01-01 07:58:31', '2019-01-01 07:58:31'),
(8, 'Bánh tôm chiên giòn', 'banh-tom-chien-gion', 'Bước 1: Tôm tươi rửa sạch, lột vỏ, cắt bỏ râu tôm, ướp với 1/2 muỗng cà phê muối, 1 muỗng cà phê đường cho đậm đà. <br>\r\nBước 2: Khoai lang rửa sạch, bào vỏ, cắt khoai lang thành từng sợi mỏng dài khoảng 0.5cm. Ngâm khoai trong nước muối pha loãng khoảng 15 phút để khoai ra hết nhựa, không bị thâm và giòn hơn khi chiên. <br>\r\nBước 3: Trộn bột mì, bột năng, nước cùng 1 muỗng cà phê đường, 1/2 muỗng cà phê muối trong 1 tô lớn, đánh đều tay cho đến khi hỗn hợp chuyển thành sền sệt. Lược bột qua rây cho bột thêm mịn mượt. <br>\r\nBước 4: Cho từ từ khoai lang và tôm vào trộn cùng hỗn hợp bột, trộn đều để khoai và tôm phủ đầy bột. <br>\r\nBước 5: Cho dầu vào chảo đun sôi. Dùng muỗng canh múc 1 muỗng đầy bột cùng khoai lang, đặt tôm lên trên mặt bánh. Khi dầu đã nóng, đưa từ từ muỗng bột vào chảo, nghiêng muỗng để đổ bánh xuống chảo dầu. Để lửa nhỏ chiên bánh cho đến khi bánh có màu vàng nâu và có mùi thơm là được. <br>\r\nBước 6: Khi bánh đã vàng đều thì vớt ra khỏi chảo, đặt vào đĩa có lót sẵn giấy ăn cho thấm bớt dầu. <br>\r\nBước 7: Nước chấm cũng giữ 1 vai trò quyết định trong món bánh tôm này. Chuẩn bị đồ chua. Tỏi, ớt băm nhuyễn. Pha nước mắm, đường, chanh, tỏi, ớt trộn đều trong 1 tô lớn. Nêm nếm thêm nước lọc sao cho nước chấm có vị chua, cay dịu rồi cho đu đủ, cà rốt vào. <br>\r\nBước 8: Bánh tôm ăn nóng kèm với rau thơm và nước chấm là ngon nhất. <br>', 'banh_tom_chien_gion.jpg', 0, 0, 7, '2019-01-01 07:58:31', '2019-01-01 07:58:31'),
(9, 'Bánh xèo tôm thịt', 'banh-xeo-tom-thit', 'Bước 1: Thịt heo rửa sạch, thái thành từng khúc ngắn cỡ nửa lóng tay út. Tôm rửa sạch, nếu dùng tôm to bạn thái làm hai, nếu dùng tôm nhỏ, bạn giữ nguyên. Giá đỗ rửa sạch. Hành tây thái sợi mỏng, hành lá băm nhỏ. <br>\r\nBước 2: Cho bột gạo, bột bắp, muối pha với nước, sau đó cho thêm nước cốt dừa, bột nghệ vào tô bột bánh xèo đã chuẩn bị sẵn, cho thêm hành lá băm, khuấy đều. <br>\r\nBước 3: Làm nóng chảo, múc khoảng 1 muỗng canh dầu ăn vào, cho hành tây vào xào thơm, kế đó, bạn cho thịt heo vào xào chín, nêm thêm ít nước mắm rồi vớt ra ngoài để riêng. Bạn cũng chiên tôm vừa chín tới rồi vớt ra ngoài. <br>\r\nBước 4: Bắc 1 cái chảo khác lên bếp, đun nóng chảo, láng đều một lớp dầu ăn. Dùng muỗng múc hỗn hợp bột bánh xèo vào, tráng mỏng. Đậy nắp lại. Thêm giá đỗ và thịt heo, tôm vào, gấp bánh xèo làm đôi, chiên chín 2 mặt. Lần lượt chiên cho đến khi hết nguyên liệu. <br>\r\nBước 5: Bạn dọn bánh ra đĩa, ăn cùng rau sống tùy thích và nước mắm chua mặn ngọt nhé. Chúc các bạn thành công và ngon miệng với món bánh xèo tôm thịt mà mình chia sẻ ở trên! <br>', 'banh_xeo_tom_thit.jpg', 0, 0, 7, '2019-01-01 07:58:31', '2019-01-01 07:58:31'),
(10, 'Bì heo trộn xoài', 'bi-heo-tron-xoai', 'Bước 1: Bì heo (Da heo) mua về rửa nước muối sạch để ráo. Cho 300gr bì heo vào nồi luộc chín cùng 5gr gừng, 5gr sả và 1 muỗng canh giấm để khử mùi và giúp bì trắng hơn. Luộc khoảng 30 phút đến khi bì chín thì vớt ra bỏ vào tô nước đá lạnh 5 phút. Thấm khô miếng bì heo và cắt thành từng sợi vừa ăn. <br>\r\nBước 2: Tép khô cho vào cối giã nhuyễn. Nấu sôi 50ml nước mắm và 50gr đường trên bếp rồi để nguội. Cho vào nước mắm 10gr tỏi băm, 10gr ớt băm, 20gr tép khô và 50ml nước cốt tắc. Trộn đều hỗn hợp là ta đã có phần sốt trộn gỏi hấp dẫn rồi! <br>\r\nBước 3: Xoài xanh và cà rốt rửa sạch gọt vỏ, bào sợi dài. Cho 300gr xoài và 50gr cà rốt vào tô lớn. Tiếp theo cho bì heo, 20gr rau răm cắt nhỏ và 20gr hành phi vào cùng. Rưới nước mắm và trộn đều cho các nguyên liệu cho hòa quyện với nhau. <br>\r\nBước 4: Cách làm món bì heo trộn xoài rất nhanh và đơn giản phải không nào, hãy thêm món này vào danh sách các món nhậu nhé, đảm bảo bạn bè và ông xã bạn sẽ rất thích vì mùi vị món bì heo trộn xoài rất hấp dẫn, vừa đủ mặn ngọt chua cay vừa giòn giòn sần sật khi ăn, đúng là món ngon khó cưỡng! <br>', 'bi_heo_tron_xoai.jpg', 0, 0, 6, '2019-01-01 07:58:31', '2019-01-01 07:58:31'),
(11, 'Cá basa áp chảo', 'ca-basa-ap-chao', 'Bước 1: Chuẩn bị nguyên liệu. Cá rửa sạch, cắt miếng vừa ăn, tránh cắt nhỏ vì khi áp chảo sẽ bị nát. Tỏi bóc vỏ, băm nhuyễn, 1 phần để ướp cá, 1 phần để phi cho thơm. <br>\r\nBước 2: Cho cá vào tô, cho gia vị nêm nếm (nước mắm, tiêu, tỏi băm, mật ong, ớt) ướp 10 phút cho cá thấm gia vị. Đun nóng dầu ăn trong chảo, thả phần tỏi còn lại vào chảo phi thơm, cho cá vào chảo. <br>\r\nBước 3: Khi một mặt cá đã vàng, dùng đũa trở mặt còn lại, cẩn thận cá bị vỡ. Tắt bếp, cho hành lá đã cắt nhuyễn lên mặt. Cho cá ra dĩa, đặt vào microwave quay 4 phút cho ráo dầu. <br>\r\nBước 4: Món Cá basa áp chảo eatclean cực kì thơm ngon, béo giòn và bổ dưỡng, ăn ngay với cơm nóng siêu ngon luôn nha. Chúc cả nhà thành công! <br>', 'ca_basa_ap_chao.jpg', 0, 0, 5, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(12, 'Canh củ sen hầm táo đỏ', 'canh-cu-sen-ham-tao-do', 'Bước 1: Ngâm nở hạt sen, táo đỏ, nấm, hoài sơn (củ mài) khoảng 45 phút. Đổ nước dừa vào nồi, cho thêm nước vào để có nước canh khoảng 2 tô lớn. Cho hạt sen và hoài sơn vào nấu trước. Nấm sau khi ngâm nở thì vắt cho thật ráo nước. Nấu khoảng 15 phút rồi cho táo đỏ và nấm vào nấu cùng. <br>\r\nbước 2: Nêm vào nồi 1 muỗng canh đường phèn, 1/2 muỗng cà phê muối, 1 muỗng cà phê hạt nêm. Củ sen gọt vỏ, thái lát mỏng rồi cho vào nồi. Cà rốt gọt vỏ. cắt thành lát dày. Sau khi nấu được khoảng 20 phút nữa thì cho cà rốt vào. Nấu đến khi cà rốt chín là hoàn thành. <br>\r\nBước 3: Món canh củ sen hầm táo đỏ với vị ngọt thanh từ nước dừa, đường phèn, củ sen sẽ là món ăn lí tưởng cho những ngày bạn thấy ngán thịt cá. Cách làm lại đơn giản, không quá cầu kì hay đòi hỏi nguyên liệu đắt tiền, khó mua. Còn chờ gì nữa mà không nấu thử món này ngay để đãi cả nhà nào. <br>', 'canh_cu_sen_ham_tao_do.jpg', 0, 0, 4, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(13, 'Cánh gà om cay', 'canh-ga-om-cay', 'Bước 1: Rửa cánh gà và thấm khô nước, chọc lỗ bằng nĩa cho dễ ngấm gia vị. Hành lá rửa sạch, thái nhuyễn. Gừng cắt gừng thái nhỏ hạt lựu. Ớt đỏ thái nhỏ. <br>\r\nBước 2: Nước sốt ướp thịt gồm:50ml nước tương, 30ml rượu gạo, 1/2 muỗng cà phê bột ớt, hạt tiêu đen, 1/2 muỗng cà phê muối, 1 muỗng canh đường, gừng và hành lá, khuấy đều. Cho cánh gà vào và ướp chúng trong tủ lạnh ít nhất 2 giờ. <br>\r\nBước 3: Đun nóng 2 muỗng canh dầu ăn, cho cánh gà và sốt ướp vào nồi, thêm 100ml nước lọc đun sôi rồi hạ nhỏ lửa. Đậy nắp vung đun cho nước gần cạn. Sau đó mở nắp đun tiếp cho sốt cạn và áo đều lên gà là được. <br>\r\nBước 4: Từng miếng cánh gà om cay thơm đậm đà được áo lên mình 1 màu nâu cánh gián sáng bóng, chỉ cần trông thôi đã thèm ăn ngay rồi. Thịt cánh gà chín béo mềm, vị mặn ngọt, cay thơm rất là ấm lòng luôn nhé! <br>', 'canh_ga_om_cay.jpg', 0, 0, 13, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(14, 'Canh mồng tơi nấu ghẹ', 'canh-mong-toi-nau-ghe', 'Bước 1: Ghẹ rửa sạch và cho vào nồi hấp chín. Mồng tơi tách lá, rửa sạch, để ráo nước. Chuẩn bị các loại gia vị nêm. <br>\r\nBước 2: Ghẹ hấp xong vớt ra tô và tách làm 2 phần, tiến hành lấy gạch. Sau đó, cho gạch vào nồi nấu làm nước dùng, phần còn lại của ghẹ để cho vào nồi sau. <br>\r\nBước 3: Bật bếp và đun sôi nồi nước dùng, sau đó cho phần thịt ghẹ còn lại vào nồi nấu chín. Tiếp tục cho rau mồng tơi cắt nhỏ vào nồi, nêm gia vị vừa ăn là xong rồi đó. Tắt bếp, múc canh ra chén thưởng thức thôi nào. <br>\r\nBước 4: Món Canh mồng tơi nấu ghẹ này phải ăn nóng mới tận hưởng hết mùi vị thơm ngon và ngọt từ ghẹ tươi nhé. Cuối tuần làm ngay cho cả nhà tẩm bổ nào. <br>', 'canh_mong_toi_nau_ghe.jpg', 0, 0, 8, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(15, 'Cháo hải sản', 'chao-hai-san', 'Bước 1: Đâu tiên đem tôm rửa sạch để ráo. Thịt cua xé nhỏ. Thái nhỏ hạt lựu: cà rốt, bí ngòi, củ cải và hành tây. Gạo vo sạch cho vào nồi lớn. <br>\r\nBước 2: Rưới 1/2 muỗng canh dầu mè vào nồi gạo, đun lửa vừa, đảo đều. Tiếp đến cho cà rốt, bí ngòi, hành tây và củ cải vào đảo đều. Sau đó đến lượt là thịt cua và tôm. <br>\r\nBước 3: Đổ 1.8 lít nước dùng (nấu từ cá cơm và rong biển) vào nồi, khuấy đều, đun sôi với lửa lớn rồi mở nhỏ lửa, nấu đến khi cháo chín nhừ. Nêm vào 1 muỗng cà phê muối. Đặt 1 lá phô mai lên trên nồi cháo, đun tan chảy phô mai, khuấy đều rồi tắt bếp. <br>\r\nBước 4: Cháo hải sản tươi ngon là món ăn lý tương cho bữa sáng của cả nhà. Đây là món dinh dưỡng thích hợp tẩm bổ cho người bệnh mới khỏi. Rất có lợi cho sự tăng trưởng của trẻ. <br>', 'chao_hai_san.jpg', 0, 0, 1, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(16, 'Chuối sấy giòn tẩm caramel', 'chuoi-say-gion-tam-caramel', 'Bước 1: Chuẩn bị nước ngâm: vắt chanh vào tô nước ngâm chuối để không bị đen, nhớ để lại 1 miếng chanh để cho vào nước đường. Chuối lột vỏ, bào thành lát mỏng, khi làm nhớ nhúng cả tay và chuối vào tô nước để không bị dính nhựa chuối. <br>\r\nBước 2: Ngâm chuối với nước chanh loãng 10 phút rồi vớt ra để ráo, trải chuối ra để dễ khô nước hơn nha. <br>\r\nBước 3: Chanh cắt thành từng miếng. Gừng cắt lát mỏng cho vào cối giã nát rồi hòa cùng 50ml nước lọc bỏ xác. Cho nước gừng vào chảo cùng đường thốt nốt, vừa xào gừng vừa trộn cho đường nhanh tan và không bị cháy. <br>\r\nBước 4: Làm nóng chảo, cho dầu vào chiên chuối với lửa lớn cho vàng rồi vớt ra rổ có lót giấy ăn cho ráo dầu. Chuối sau khi chiên giòn tan không thấm dầu, nếu bạn không thích ăn ngọt có thể dừng ở bước này, cất chuối vào hộp kín dùng dần. <br>\r\nBước 5: Nếu ăn ngọt thì chúng ta tẩm thêm caramel nha. Đun chảo nước gừng, đường thốt nốt cho keo lại rồi tắt bếp vắt chanh vào. Cho chuối lát đã chiên vào chảo, đảo đều cho chuối bọc đều caramel rồi rắc mè vàng rang chín lên là xong đó. <br>\r\nBước 6: Món snack chuối này tuy chiên bằng dầu nhưng không ngấm dầu nên không ngấy, ăn vào có vị béo giòn rụm hòa tan cùng vị thơm thơm cay cay của gừng, ngọt ngào của caramel. Món ăn vặt này rất thích hợp nhâm nhi với tách trà cùng bạn bè, vừa ăn vừa xem phim, party... Chúc bạn thành công. <br>\r\n', 'chuoi_say_gion_tam_caramel.jpg', 0, 0, 2, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(17, 'Đậu nhồi thịt', 'dau-nhoi-thit', 'Bước 1: Ngâm miến và nấm mèo vào nước khoảng 30 phút cho nở đều. Sau đó, rửa sạch qua nhiều nước rồi đem đi cắt nhuyễn. <br>\r\nBước 2: Xay nhuyễn 2 trái cà chua. Ngò rí rửa sạch, cắt nhỏ. Đậu hũ rửa sạch, cắt một phần nhỏ ngang thân, lấy bớt phần đậu trắng bên trong như hình bên. <br>\r\nBước 3: Băm nhuyễn hành tím và đầu hành lá rồi đem trộn với thịt băm, miến và nấm mèo. Sau đó, cho vào hỗn hợp 1/3 muỗng cà phê bột ngọt, 2/3 muỗng cà phê muối, 1/3 muỗng cà phê tiêu rồi trộn đều. <br>\r\nBước 4: Nấu nồi nước sôi. Nhồi hỗn hợp trên vào đậu hủ cho vừa phải. Đặt đậu hủ đã nhồi vào tô, cho vào nồi, hấp trong vòng 15 phút. <br>\r\nBước 5: Bắt chảo lên bếp, cho vào 20 ml dầu ăn. Dầu nóng thì cho vào 1 tép tỏi đập dập, phi thơm rồi cho cà chua xay vào. Nêm 1/3 muỗng cà phê muối, 1 muỗng canh nước mắm, 1/2 muỗng cà phê đường, 1 muỗng cà phê bột ngọt. Khi sôi thì cho tiếp 50 ml sốt cà chua và khoảng nửa chén nước. <br>\r\nBước 6: Cho hết đậu hũ nhồi đã hấp chín cùng với nước hấp vào chảo sốt cà chua. Đậy nắp chảo lại nấu lửa vừa cho đậu thấm sốt khoảng 5-7 phút là được. <br>\r\nBước 7: Bày trí ra đĩa, rắc ngò rí lên trên là có ngay món đậu nhồi thịt sốt cà chua thơm ngon cho bữa cơm của gia đình. <br>', 'dau_nhoi_thit.jpg', 0, 0, 5, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(18, 'Đậu phộng da cá giòn', 'dau-phong-da-ca-gion', 'Bước 1: Đậu phộng mua về cho vào tô, thêm 1 quả trứng gà, 5g muối rồi trộn đều lên. Sau đó, cho vào 2 muỗng canh bột mì và trộn sau cho bột bám đều hết vào hạt đậu phộng, nêm thêm 1 muỗng bột ngũ vị hương, 1 muỗng mè rang, đảo thêm vài lần cho tất cả bám đều vào đậu phộng. <br>\r\nBước 2: Khi đậu phộng đã áo đều lớp bột thì bạn rây đậu để loại bỏ bớt phần bột thừa bám xung quanh đậu. Cho dầu ăn vào chảo đun nóng, ngay khi dầu sôi thì cho đậu phộng vào chiên đến khi chín vàng, giòn rụm lớp vỏ bên ngoài thì vớt ra cho ráo dầu. Một lần chiên lượng vừa phải để không bị dính và đậu không chín đều nha. <br>\r\nBước 3: Vậy là Tết này cả nhà đã có ngay món đậu phộng da cá giòn rụm để nhâm nhi mà không phải mua bên ngoài rồi đó. Cách làm cũng khá đơn giản nên chị em nội trợ lưu lại công thức ngay nhé. <br>', 'dau_phong_da_ca_gion.jpg', 0, 0, 2, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(19, 'Đậu sốt nấm cà chua', 'dau-sot-nam-ca-chua', 'Bước 1: Đậu hũ non rửa sạch, cắt miếng nhỏ hình vuông. Hành lá cắt nhỏ, cà chua rửa sạch, cắt miếng vừa ăn. <br>\r\nBước 2: Trụng qua đậu hũ non với nước nóng. Phi thơm 2 muỗng canh dầu mè với đầu trắng hành lá, cho cà chua vào, đảo đều. <br>\r\nBước 3: Tiếp theo, cho đậu hũ non vào cùng, nấu nhỏ lửa khoảng 3 phút. Nêm gia vị 1 muỗng canh sốt cà chua, 1 muỗng cà phê muối, 1 muỗng canh đường trắng, 1 muỗng canh nước tương, 1 muỗng cà phê hạt nêm chay cho vừa ăn. <br>\r\nBước 4: Tắt bếp, cho món ăn ra đĩa hoặc chén, rắc hành lá lên là xong. Chúc các bạn ngon miệng bên gia đình nhé! <br>', 'dau_sot_nam_ca_chua.jpg', 0, 0, 4, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(20, 'Gà chiên xù', 'ga-chien-xu', 'Bước 1: Đùi gà rửa sạch với giấm và muối sau đó thấm khô nước, nếu không có thời gian ướp gà, bạn dùng dao khứa vài đường chéo trên đùi gà để khi ướp thịt nhanh ngấm gia vị hơn nhé! <br>\r\nBước 2: Cho đùi gà vào tô cùng với 1/4 muỗng cà phê muối, 1/4 muỗng cà phê tiêu, 1/2 muỗng cà phê hạt nêm, 1 muỗng canh nước tương đậm đặc, 1 muỗng canh bột tỏi, 1 muỗng canh rượu trắng. Đeo bao tay vào sau đó bóp nhẹ cho thịt được ngấm đều gia vị, ướp thịt khoảng 1 tiếng hoặc để ngăn mát tủ lạnh qua đêm sẽ càng ngon hơn. <br>\r\nBước 3: Cho xửng hấp lên bếp đun sôi nước rồi xếp đùi gà vào, hấp cho đến khi đùi gà chín thì lấy ra để nguội. <br>\r\nBước 4: Đập trứng gà ra bát đánh cho tan, bột mì, bột chiên xù cho ra đĩa sau đó lấy đùi gà lăn qua bột mì rồi nhúng vào trứng gà, cuối cùng bạn cho đùi gà vào đĩa bột chiên xù, lăn đều cho đùi gà bám đều 1 lớp bột chiên xù. Làm lần lượt cho hết nguyên liệu. <br>\r\nBước 5: Đun nóng nhiều dầu ăn trong nồi nhỏ, thả nhẹ nhàng đùi gà đã tẩm bột vào chiên cho đến khi chín vàng giòn đều thì vớt ra để ráo dầu. Khi gà chiên hơi nguội bớt là có thể dùng ngay nhé! Chấm cùng tương ớt, tương cà hay các loại sốt mà bạn ưa thích. <br>', 'ga_chien_xu.jpg', 0, 0, 13, '2019-01-01 08:42:49', '2019-01-01 08:42:49'),
(21, 'Hẹ xào giá đỗ', 'he-xao-gia-do', 'Bước 1: Giá đỗ mua về nhặt sạch, rửa sạch với nhiều nước, sau đó đem chần giá đỗ qua nước sôi khoảng 30 giây rồi vớt ra để ráo nước. Hẹ rửa sạch, cắt khúc ngắn 2-3cm. <br>\r\nBước 2: Đun nóng 2 muỗng canh dầu ăn, cho hẹ và giá đỗ vào xào. Xào lửa vừa cho giá hẹ dịu xuống. Nêm thêm 1/2 muỗng cà phê muối, 1 muỗng cà phê hạt nêm và 1/2 muỗng cà phê đường, xào tiếp 1 phút cho ngấm gia vị là được. <br>\r\nBước 3: Hẹ xào giá đỗ đơn giản mà ngon cơm. Món xào giúp chống ngán rất hiệu quả. Mình thường dùng món này ăn kèm với cơm sau những bữa đám tiệc nhiều món ăn dầu mỡ. <br>', 'he_xao_gia_do.jpg', 0, 0, 6, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(22, 'Kem bơ cốt dừa', 'kem-bo-cot-dua', 'Bước 1: Bơ xẻ đôi, bỏ hạt, nạo lấy phần thịt. Chanh vắt lấy nước cốt, bỏ hạt nếu có. Cho bơ, nước cốt dừa, muối, dầu olive vào máy xay và xay nhuyễn hỗn hợp. <br>\r\nBước 2: Cho bơ vào lọ thủy tinh dùng dần. Tự làm bơ sạch tại nhà có thể giúp bạn vừa có được sản phẩm bơ tươi sạch, thơm béo sử dụng lâu dài, vừa tiết kiệm được nhiều chi phí hơn khi mua ngoài hàng. <br>', 'kem_bo_cot_dua.jpg', 0, 0, 11, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(23, 'Khoai môn chiên nước mắm', 'khoai-mon-chien-nuoc-mam', 'Bước 1: Khoai môn các bạn gọt vỏ, bào lát mỏng như hình. Ngâm khoai vào nước muối loãng khoảng 3 phút vớt ra để ráo. Các bạn nhớ đeo bao tay lúc gọt khoai để tránh bị ngứa. <br>\r\nBước 2: Chuẩn bị chảo dầu nóng, cho khoai vào chiên. Chiên món này cần nhiều dầu, canh lửa vừa phải để lát khoai không bị cháy sém mà giòn đều. Khi khoai đã giòn vớt ra đĩa có lót giấy thấm dầu. Đợi khoai vừa nguội các bạn cho vào túi bóng hoặc hũ kín cột/đậy lại tránh để lâu ngoài không khí khoai bị ỉu mất ngon. Chiên lần lượt hết số khoai còn lại. <br>\r\nBước 3: Chuẩn bị sốt nước mắm: 1 muỗng canh nước mắm, 1 muỗng canh đường, 1/4 muỗng canh hạt nêm, 1/2 muỗng canh dầu ăn khuấy đều cho tan. Cho sốt lên chảo, đun cho sốt hơi sánh lại, cho khoai vào đảo nhẹ và nhanh tay để sốt bám đều vào các miếng khoai. Nếu lượng khoai nhiều, các bạn chia sốt và khoai ra thành nhiều phần, lần lượt trộn từng phần là được. <br>\r\nBước 4: Khoai môn chiên nước mắm đợi nguội thì cất khoai vào hũ kín để giữ khoai giòn ăn dần nhé! Không nên để lâu ngoài giò vì sẽ làm khoai bị ỉu đấy! <br>', 'khoai_mon_chien_nuoc_mam.jpg', 0, 0, 14, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(24, 'Khoai tây chiên', 'khoai-tay-chien', 'Bước 1: Khoai tây gọt vỏ, cắt thanh dài, ngâm nước muối cho khỏi bị thâm khoai. <br>\r\nBước 2: Vớt khoai ra rổ để ráo nước. Cho một ít muối và 1 muỗng canh bột chiên giòn vào khoai, trộn đều. <br>\r\nBước 3: Đun dầu thật sôi, đảm bảo lượng dầu ngập mặt khoai. Chiên khoai trên lửa lớn đến khi khoai chuyển màu vàng, có độ giòn cứng là được. <br>', 'khoai_tay_chien.jpg', 0, 0, 3, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(25, 'Lẩu cua biển', 'lau-cua-bien', 'Bước 1: Tôm khô, mực khô nướng xé nhỏ. Nấm rơm làm sạch, ngâm muối rồi để ráo, cắt đôi. Xương heo hầm lấy nước dùng. Cà chua rửa sạch, cắt múi cau. Hành tây bóc vỏ, cắt miếng nhỏ. Hành tím, ngò om, tỏi bóc vỏ, rửa sạch cắt nhỏ. Ớt cắt lát. <br>\r\nBước 2: Cua sau khi rửa sạch, bẻ càng, tách mai và lọc gạch riêng ra một chén. Ướp cua với tỏi, tiêu, đường, bột ngọt, nước mắm. <br>\r\nBước 3: Đặt nồi lên bếp, phi thơm hành tím, sả băm, sau đó cho cà chua vào xào, tiếp đến cho cua đã ướp gia vị vào đảo đều tay tới khi cua hơi ngả vàng. <br>\r\nBước 4: Cho nước lọc vào nồi cua nấu. Cua mau chín nên khi nước sôi là cho nấm rơm, hành tây vào nêm nếm gia vị vừa ăn. <br>\r\nBước 5: Lấy 1 chảo nhỏ, phi thơm hành tím, cho tôm khô và gạch cua vào đảo nhanh tay cho gạch dậy mùi thơm (cách này để gạch bớt tanh và dậy mùi lẩu) để riêng. Cho hỗn hợp gạch cua đã xào vào nồi lẩu, rắc ít rau thơm như ngò gai, ngò om. <br>\r\nBước 6: Dọn dùng kèm rau, bún. Lẩu khi ăn đun sôi nước dùng, nhúng rau, chan bún... Lẩu ăn ngon khi dùng nóng, vì đây là lẩu hải sản. Nên cho ớt để giảm độ tanh, nếu ko ăn cay được, bạn có thể thay thế bằng ớt sừng trâu để có độ hăng của ớt. <br>', 'lau_cua_bien.jpg', 0, 0, 16, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(26, 'Lẩu cua Hàn Quốc', 'lau-cua-han-quoc', 'Bước 1: Rửa sạch cua, tách bỏ phần yếm và các lông cua phía bên trong yếm. Lấy phần mai cua và bẻ đôi phần thân. <br>\r\nBước 2: Thái củ cải trắng và bí xanh thành các miếng vừa ăn. Củ hành lá, ớt sừng thái xéo. Nấm kim châm, nấm sò và rau cải cúc rửa sạch cắt bỏ phần gốc. Trộn đều các gia vị trong phần sốt. <br>\r\nBước 3: Cho 1,4 lít nước vào trong nồi, tiếp đó cho thêm cùng cải trắng vào nấu cùng. Khi nước trong nồi sôi , cho hết phần sốt đã chuẩn bị từ trước vào. Thêm cua vào nồi nước dùng. <br>\r\nBước 4: Xếp các nguyên liệu rau củ còn lại vào nồi và từ từ thưởng thức thôi. Nồi nước dùng màu đỏ tươi, đậm đà chuẩn vị Hàn Quốc. Khi ăn kèm với các loại nấm, rau và đặc biệt là thịt cua tươi, săn quả thật rất kích thích vị giác của tất cả mọi người. Hãy thử làm món lẩu cua Hàn Quốc này chiêu đãi gia đình vào dịp cuối tuần nhé! <br>', 'lau_cua_han_quoc.jpg', 0, 0, 16, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(27, 'Lẩu cua Nam Bộ ', 'lau-cua-nam-bo', 'Bước 1: Mực rửa sạch, cắt miếng vừa ăn. Cua đồng rửa sạch, nghều lấy gạch cua, phần vỏ cua cho vào máy xay sinh tố cùng 1 chén nước, xay nhuyễn, lọc lấy nước, bỏ bã. <br>\r\nBước 2: Cua biển, tôm tươi, nghêu rửa sạch, để ráo. <br>\r\nBước 3: Nấm rơm, nấm kim châm cắt bỏ gốc. Cà chua rửa sạch, cắt múi cau. <br>\r\nBước 4: Làm nóng 2 muỗng canh dầu ăn, cho cà chua vào, xào khoảng 2 phút. <br>\r\nBước 5: Tiếp theo, cho gạch cua đồng, nước cua, cá viên, nước cốt me, 2 muỗng canh đường trắng, 1 muỗng canh nước màu, 1 muỗng cà phê sa tế, 1 muỗng canh nước mắm, 1 muỗng cà phê hạt nêm, 1 muỗng cà phê muối, nấu nhỏ lửa khoảng 5 phút. <br>\r\nBước 6: Khi ăn bạn chỉ việc cho cua biển, tôm tươi, nghêu, mực vào, nấu sôi là được. Món này ăn kèm bún tươi, nấm rơm, nấm kim châm và các loại rau ngon tuyệt! <br>', 'lau_cua_nam_bo.jpg', 0, 0, 16, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(28, 'Lẩu gà ác \r\n', 'lau-ga-ac', 'Bước 1: Chuẩn bị đầy đủ nguyên liệu: Sả chia 2 phần, 1 phần băm nhuyễn và 1 phần cắt khúc rồi đập dập. Hành tím, tỏi, ớt băm nhuyễn. Gà ác rửa sạch với nước muối và rượu trắng, sau đó chặt khúc. Củ cải trắng và cà rốt gọt vỏ, cắt miếng chéo. Các loại rau như: rau dền, tần ô, rau má rửa sạch, để ráo nước. <br>\r\nBước 2: Đun nóng nồi, thêm chút dầu ăn rồi cho tỏi, hành tím, sả vào phi thơm. Chế nước vào nồi lượng vừa phải, tiếp đó cho cà rốt, củ cải trắng vào nồi, nêm nếm gia vị cho vừa ăn. Nấu sôi nồi nước dùng cho sôi để cà rốt, củ cải ra chất ngọt. <br>\r\nBước 3: Khi nước dùng đã đạt được hương vị mong muốn thì bạn cho gá ác vào nồi, tiếp tục nấu sôi để thịt gà chín mềm. Có thể nêm nếm lại gia vị nếu như nước dùng bị lạc nha. Kiểm tra thấy thịt gà đã chín thì cho hành là xắt nhỏ vào, rắc thêm chút tiêu để tăng hương vị là có thể tắt bếp rồi nha. <br>\r\nBước 4: Dọn lẩu ra bàn cùng với các loại rau đã chuẩn bị và ăn kèm cùng với bún tươi nha. Món Lẩu gà ác thơm ngon này cực kì hấp dẫn khi dùng vào những ngày trời lành lạnh đấy. Chị em nhanh tay lưu công thức lại và nấu ngay nhé. <br>', 'lau_ga_ac.jpg', 0, 0, 16, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(29, 'Lẩu gà Thái Lan', 'lau-ga-thai-lan', 'Bước 1: Gà mua về làm sạch rửa bằng nước muối cho bớt mùi, cắt nhỏ từng khúc. Rau cải, tàn ô cắt gốc rửa sạch với nước muối. Bắp chuối rửa sạch bằng nước muối. <br>\r\nBước 2: Cà chua rửa sạch bổ làm tư, thơm rửa sạch cắt lát nhỏ, sả, hành tím, giềng rửa sạch lột vỏ bằm nhỏ. Sả rửa sạch dùng chày đập nát. Lấy một trái ớt cắt lát. <br>\r\nBước 3: Cho dầu vào nồi nóng, bỏ tỏi, hành tím, rềng bằm nhỏ vào nồi xào cho thơm, cho cà chua, thơm vào đảo đều, cho thêm 1,5 lít nước vào nồi. <br>\r\nBước 4: Cho gói gia vị lẩu Thái, sả cây vào nồi, đun cho sôi. Sau đó cho gà, ớt nguyên trái, ớt cắt lát vào nồi đun tiếp đến khi sôi lại là được, nêm mắm, đường, hạt nêm, bột ngọt vào nếm thử cho đến khi vừa miệng, thấy gà đã chín thì tắt bếp. <br>\r\nBước 5: Khi nào ăn thì đun lại cho nóng, bỏ rau, bún vào tô múc nước lẫu chen vào. Rất đơn giản đúng không nào, thế là bạn đã có một nồi lẩu vừa dễ làm mà ăn lại cực kì ngon. <br>', 'lau_ga_thai_lan.jpg', 0, 0, 16, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(30, 'Lẩu Thái hải sản', 'lau-thai-hai-san', 'Bước 1: Rau muống, rau nhút nhặt khúc ngắn vừa ăn, rửa sạch. Nấm kim châm cắt bỏ chân. Xếp rau muống, rau nhút, nấm và bắp chuối, bông bí, cà chua ra đĩa. Bún tươi hoặc mì có thể trụng qua nước sôi cho mềm rồi dọn sẵn ra dĩa. <br>\r\nBước 2: Phần hải sản: tôm tươi rửa sạch, mực làm sạch cắt khoanh, phi lê cá basa rửa sạch cắt lát hoặc cắt khúc, nghêu ngâm với ớt và muối cho ra bớt cát. Xếp tôm, mực, nghêu, phi lê cá, thịt bò ra đĩa. <br>\r\nBước 3: Bắc nồi lên bếp, cho vào 2 muỗng canh dầu ăn, chờ dầu nóng thì cho 50gr sả cây đập dập, 30gr riềng cắt lát đập dập, 5 trái ớt trái đập dập vào xào thơm. Sau đó cho thêm 100gr cà chua cắt múi cau và 100gr thơm cắt lát vào nồi, thêm 1/2 muỗng cà phê muối vào xào chung cho rau củ nhanh mềm để tạo màu đỏ đẹp mắt. Khi cà chua và thơm mềm thì chế vào nồi 1.5 lít nước lọc rồi đun sôi, hớt bỏ bọt dơ. <br>\r\nBước 4: Nêm nước lẩu với 100gr đường trắng, 100gr me, 50ml nước mắm, 50gr tương ớt, 30gr hạt nêm, 30gr ớt sa tế cho đủ vị chua cay mặn ngọt đậm đà. Cuối cùng cho 5 lá chanh đã tước bỏ gân, vò nát vào nồi, nấu thêm 2 phút cho thơm là hoàn tất phần nước lẩu. <br>\r\nBước 5: Khi ăn đun sôi nước lẩu, rồi lần lượt nhúng các loại hải sản và tôm thịt vào chờ chín thì thưởng thức thôi. <br>', 'lau_thai_hai_san.jpg', 0, 0, 16, '2019-01-01 10:46:03', '2019-01-01 10:46:03'),
(31, 'Măng tây nướng trộn phô mai', 'mang-tay-nuong-tron-pho-mai', 'Bước 1: Măng tây cắt bỏ gốc, rửa sạch và để ráo nước. Cho măng tây vào tô, rưới 3 muỗng dầu olive cùng 1/4 muỗng muối, 1/4 muỗng tiêu, trộn thật đều cho tất cả thấm đều gia vị. Mở lò nướng ở 175 độ C, cho măng tây lên khay và đặt vào lò nướng khoảng 5 - 7 phút đến khi măng chín, vàng giòn thì lấy ra. Cắt măng tây thành từng khúc nhỏ vừa ăn. <br>\r\nBước 2: Cho măng tây vừa cắt vào tô, rưới thêm dầu olive, 1 muỗng vỏ chanh bào, phô mai feta bẻ nhỏ, 1 muỗng nước cốt chanh và trộn đều lên. Bạn có thể nên thêm chút muối cho đậm vị nha. Vậy là hoàn thành món ăn rồi đó. <br>\r\nBước 3: Bạn có thể thêm ngay món Măng tây nướng trộn phô mai này vào thực đơn chay của mình nhé. Hương vị giòn ngọt tự nhiên của măng thấm đậm gia vị kèm phô mai beo béo rất tuyệt đấy. Hãy thử làm ngay nhé. <br>', 'mang_tay_nuong_tron_pho_mai.jpg', 0, 0, 4, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(32, 'Măng tây trộn sốt say', 'mang-tay-tron-sot-cay', 'Bước 1: Măng tây cắt bớt phần gốc, rửa sạch, để ráo nước. Sau đó, cắt măng tây thành từng khúc dài cỡ 2cm. Đun sôi nồi nước, cho măng tây vào luộc cho chín mềm nhưng vẫn giữ độ giòn cỡ 1 - 3 phút. Vớt măng ra cho vào tô nước đá rồi lấy ra để ráo. <br>\r\nBước 2: Nước sốt: trộn đều 2 muỗng tương ớt, 1 muỗng đường, 2 muỗng giấm, 1/2 muỗng tỏi băm, 1 muỗng dầu mè, 1/2 muỗng mè rang vào trong chén nhỏ. Cho măng tây đã luộc chín vào tô lớn, rưới hỗn hợp sốt tương vừa chuẩn bị vào và trộn thật đều lên là hoàn thành. Xếp măng cùng sốt ra dĩa và thưởng thức. <br>\r\nBước 3: Món măng tây trộn sốt cay vừa ngon về hương vị vừa tốt cho sức khỏe của chúng ta lắm đấy. Bạn hãy thêm ngay món ăn hấp dẫn, bổ dưỡng này vào thực đơn cả nhà nha. <br>', 'măng_tay_tron_sot_cay.jpg', 0, 0, 6, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(33, 'Mướp xào nấm đùi gà', 'muop-xao-nam-dui-ga', 'Bước 1: Chuẩn bị nguyên liệu. Mướp bảo vỏ, thái khúc vừa ăn. Tỏi bốc vỏ,băm nhuyễn. Nấm đùi gà thái lát dày vừa. Hành lá cắt nhuyễn để nêm. <br>\r\nBước 2: Cho dầu ăn vào chảo, thêm tỏi băm phi thơm, cho mướp vào thêm 1 ít nước ấm, đậy nắp. Sau đó cho nấm vào trộn đều, đậy nắp 3 phút, nêm nếm gia vị, dầu hào rồi trộn đều là có thể tắt bếp. <br>\r\nBước 3: Múc ngay ra dĩa dùng ngay với cơm nóng, cho hành lá cắt nhuyễn và tiêu xay lên bề mặt cho vị ngon đậm đà. Chúc cả nhà thành công nha! <br>', 'muop_xao_nam_dui_ga.jpg', 0, 0, 4, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(34, 'Mì Ý vị nghêu', 'mi-y-vi-ngheu', 'Bước 1: Nghêu ngâm cho nhả hết cát. Rửa sạch vỏ qua nhiều lần nước. Rau mùi rửa sạch, cắt nhuyễn. <br>\r\nBước 2: Nấu nước sôi, cho mì vào trụng. Lấy tay bấm vào một cộng mì bất kỳ, nếu thấy mì mềm, vớt mì ra và cho vào ngay nước lạnh. Ngâm khoảng 2 phút vớt ra để trên rổ cho ráo nước. <br>\r\nBước 3: Cho dầu olive và bơ vào chảo rồi đun nóng ở lửa vừa. Khi dầu đã nóng và bơ tan chảy hết, bạn cho tỏi băm vào rồi phi trong khoảng 1’. Sau đó, thêm rượu trắng vào chảo. <br>\r\nBước 4: Cho nghêu vào chảo rồi nấu trong khoảng 5’. Đến khi nghêu há miệng như trong hình là được. Chú ý gắp bỏ những con nghêu không mở miệng ra nhé! <br>\r\nBước 5: Nêm nếm muối, bột ngọt vào. Rắc mùi tây vào cùng với nghêu. Nếu không thích mùi tây thì bạn có thể thay bằng húng quế cũng được. <br>\r\nBước 6: Nếu thích hương vị đậm, bạn có thể thêm một ít rượu vang nữa vào cùng rồi xóc đều lên cho nghêu ngấm. <br>\r\nBước 7: Cuối cùng, bạn gắp mì ra đĩa, cho nghêu lên trên, rồi chan phần nước sốt nghêu vào cùng là xong rồi. <br>\r\nBước 8: Món spaghetti nghêu ăn theo công thức này đảm bảo sẽ rất thơm và hấp dẫn cho xem! <br>', 'mi_y_vi_ngheu.jpg', 0, 0, 12, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(35, 'Nấm hương chiên bơ', 'nam-huong-chien-bo', 'Bước 1: Rửa sạch nấm hương, dùng khăn lau sạch nấm. Sau đó đem chẻ làm 4 mỗi nấm để chúng được nhỏ và dễ ngâm gia vị. <br>\r\nBước 2: Đun chảo gang trên lửa lớn, thêm nấm hương vào đun khoảng 2 phút. Sau đó mới lật nấm và đun thêm 1-2 phút nữa. Nấm sẽ chuyển sang màu nâu vàng và tiết ra ít nước. Giảm nhiệt xuống mức trung bình và tiếp tục đun, thỉnh thoảng đảo đều. Khi hơi nước bốc hơi hết lên và nấm bắt đầu chuyển sang màu nâu đỏ sẫm với những đốm vàng, đun thêm 5-8 phút nữa. <br>\r\nBước 3: Tắt bếp, thêm vào 2 muỗng canh bơ, 1 muỗng canh giấm đen, ngò tây tây xắt nhỏ. Đảo đều để áo và phục vụ ngay lập tức. <br>\r\nBước 4: Bạn nên dùng chảo gang dày để chế biến nấm hương chiên bơ này vì những nồi kim loại khác thì nhiệt khó kiểm soát khiến nấm dễ bị khét. Nếu dùng bơ thực vật thì món này cho thể bỏ vảo thực đơn ăn chay cũng được nhé! <br>\r\n', 'nam_huong_chien_bo.jpg', 0, 0, 4, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(36, 'Nước ép chanh dây', 'nuoc-ep-chanh-day', 'Bước 1: Chanh dây cắt làm đôi, dùng muỗng múc lấy phần ruột bên trong trái chanh dây, cho ra chén. <br>\r\nBước 2: Cho lá bạc hà, 2 muỗng canh đường trắng, 2 muỗng canh nước cốt chanh vào ly, dầm nhuyễn. <br>\r\nBước 3: Cuối cùng, cho nước chanh dây, 30ml nước lọc vào, khuấy đều. Thêm đá viên và trang trí thêm lá bạc hà nếu thích nhé! <br>', 'nuoc_ep_chanh_day.jpg', 0, 0, 9, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(37, 'Pasta bông cải bơ phô mai', 'pasta-bong-cai-bo-pho-mai', 'Bước 1: Bông cải cắt miếng vừa ăn, ngâm nước muối, rửa sạch rồi để ráo nước. Nấu nồi nước sôi, cho nui vào luộc đến khi hơi mềm thì cho bông cải xanh vào luộc khoảng 2 phút nữa để cả hai cùng chín mềm. Vớt bông cải cùng nui ra rổ cho ráo nước. <br>\r\nBước 2: Trong lúc chờ nui luôc thì bạn chuẩn bị thịt gà nha. Ức gà rửa sạch, để ráo nước, ướp với chút muối và tiêu cho đậm vị. Đun nóng chảo dầu, cho ức gà vào áp chảo mỗi mặt 5 - 7 phút cho chín vàng, thơm lừng thì vớt ra, để nguội một chút rồi cắt miếng vuông. Giữ nguyên chảo, cho bơ vào đun tan chảy, chế 250ml sữa đặc vào khuấy đến khi hòa tan. Sau đó cho bột tỏi, bột ớt paprika, muối vào khuấy lên, cho tiếp phô mai Cheddar vào trộn đến khi quyện thành hỗn hợp sệt là được. <br>\r\nBước 3: Cuối cùng, thả nui, bông cải xanh cùng thịt gà vào, trộn đều lên cho tất cả hòa quyện với nhau là xong rồi đó. Vậy là chúng ta đã hoàn thành món pasta béo ngậy, thơm lừng. Múc pasta ra chén hoặc dĩa sâu lòng và thưởng thức thôi nào. <br>\r\nBước 4: Với một công thức làm pasta khá đơn giản và dễ là chị em đã có thể chuẩn bị ngay món pasta bông cải phô mai bơ béo ngậy, ngon và hấp dẫn với thịt gà đầy đủ chất dinh dưỡng cho buổi tối của cả nhà rồi đó. <br>', 'pasta_bong_cai_bo_pho_mai.jpg', 0, 0, 12, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(38, 'Pasta cà chua phô mai', 'pasta-ca-chua-pho-mai', 'Bước 1: Nấu một nồi nước sôi, cho nui vào luộc với một chút ít dầu ăn để không bị dính với nhau. Vớt nui ra xả qua chút nước lạnh và để ráo nước. Cà chua bi rửa sạch, cắt đôi. Húng quế rửa sạch, xắt nhỏ. Đun nóng chảo dầu, cho tỏi vào phi thơm rồi thả cà chua vào xào. <br>\r\nBước 2: Khi thấy cà chua đã chín mềm, ra nước thì cho 1 muỗng bơ vào cùng 1/4 muỗng muối, 1/4 muỗng tiêu, húng quế xắt nhỏ và xào đều lên. Tiếp đó cho nui đã luộc chín vào, trộn đều lên vài phút thì tắt bếp. Múc nui ra dĩa, cho phô mai Ricotta bóp nhỏ lên trên cùng ít húng quế là xong rồi đó. <br>\r\nBước 3: Dĩa pasta cà chua phô mai khá ngon và hấp dẫn với vị chua chua, beo béo thấm vào từng sợi nui tạo vị ngon đến khó cưỡng lại. Chị em có thể đổi chút khẩu vị cho cà nhà với món này cho dễ ăn nha. <br>', 'pasta_ca_chua_pho_mai.jpg', 0, 0, 12, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(39, 'Pasta hàu sốt sữa tươi', 'pasta-hau-sot-sua-tuoi', 'Bước 1: Bắt chảo phi thơm tỏi băm cho tỏi vàng đều thơm dậy mùi rồi cho thịt hàu tươi vào xào cho săn lại. Mình gợi ý các bạn mua thịt hàu sữa ở siêu thị Big C nhé. Họ có đóng gói 1 túi 200gr toàn thịt, về chỉ việc ăn không cần chà rửa mệt mỏi. <br>\r\nBước 2: Sau khi hàu săn thịt, mình cho sữa tươi vào hầm cùng hàu tươi, thịt hàu sẽ ngấm vị béo của sữa giòn giòn dai dai. Mình cho thêm hành tây cắt nhuyễn hầm cùng hàu để dậy mùi cho món pasta. <br>\r\nBước 3: Nui mình bắc nước luộc cho nở rồi vớt ra để ráo, sau khi hàu đã chín và sốt sữa tươi săn lại mình cho nui vào đảo đều. Sau đó mình nêm hạt nêm vào hỗn hợp nui và sữa cho vừa ăn. Cả nhà nếu thích ăn lạt thì nêm muối nhạt cũng được nhé. <br>\r\nBước 4: Đảo đều cho nui hòa quyện cùng hỗn hợp sốt, nấu thêm 5 phút cho săn sốt và ngấm đều hết rồi cho thêm rau mùi nếu bạn thích nhé. <br>\r\nBước 5: Cho hỗn hợp pasta ra dĩa rồi thêm rau trang trí bạn cũng có thể ăn cùng rau thơm khô nhé. <br>', 'pasta_hau_sot_sua_tuoi.jpg', 0, 0, 12, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(40, 'Pasta nấm sốt kem', 'pasta-nam-sot-kem', 'Bước 1: Cải bó xôi rửa sạch, thái nhỏ. Nấm mỡ làm sạch rồi thái lát mỏng. Tùy theo loại mì mà bạn sẽ có thời gian luộc khác nhau nên hãy luộc mì theo thời gian hướng dẫn trên bao bì nhé. Mì luộc xong, giữ lại 2 muỗng canh nước luộc mì rồi xả ráo mì. <br>\r\nBước 2: Trong lúc mì đang luộc, bạn bắc hảo lên bếp, đun nóng bơ rồi cho tỏi băm và nấm mỡ vào xào thơm trong 2-3 phút. Rắc bột mì vào đảo đều. Thêm sữa và tiếp tục đảo, đun cho đến khi hỗn hợp sôi và bắt đầu sệt lại. <br>\r\nBước 3: Cho mì vào chảo, đảo đều rồi thêm cải bó xôi, 2 muỗng canh nước luộc mì. Nêm thêm muối và tiêu hoặc các gia vị khác cho vừa miệng, khi cải bó xôi chín là bạn có thể tắt bếp được rồi. <br>\r\nBước 4: Đến với công thức Pasta khá đơn giản này, bạn có thể tự làm cho mình và cả nhà cùng ăn. Với mì mềm dai hòa quyện trong nước sốt béo ngậy từ kem cùng nấm dai sựt, Pasta nấm sốt kem chính là món ăn tuyệt vời mà bạn có thể đổi món cho mọi người. <br>', 'pasta_nam_sot_kem.jpg', 0, 0, 12, '2019-01-01 15:22:58', '2019-01-01 15:22:58'),
(41, 'Pasta nghêu sốt rượu', 'pasta-ngheu-sot-ruou', 'Bước 1: Tùy theo loại mì mà bạn sẽ có thời gian luộc khác nhau nên hãy luộc mì theo thời gian hướng dẫn trên bao bì nhé. Mì luộc xong, giữ lại 2 muỗng canh nước luộc mì rồi xả ráo mì. <br>\r\nBước 2: Nghêu làm sạch. Đun nóng dầu olive trong chảo, cho tỏi băm vào phi thơm, cho bột ớt vào đảo đều. Cho nghêu và rượu trắng vào chảo, xào trong khoảng 3-6 phút. Nếu nghêu mở nắp đã thì bạn tắt lửa và cho ra ngoài ngay nhé. <br>\r\nBước 3: Cho mì vào chảo, đảo đều, thêm 2 muỗng canh nước luộc mì đã được giữ lại vào chảo. Cho phần nghêu trở lại chảo, rắc ngò tây băm lên, nêm thêm muối và tiêu, đảo đều lần nữa rồi tắt bếp. <br>\r\nBước 4: Gắp mì ra đĩa và thưởng thức. Món Pasta nghêu sốt rượu nóng hổi, thơm ngon này đảo bảo sẽ hấp dẫn cả nhà trong bữa ăn hôm nay. Chỉ với vài bước đơn giản, dễ làm, bạn cũng có thể trổ tài đấy! <br>', 'pasta_ngheu_sot_ruou.jpg', 0, 0, 12, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(42, 'Pasta phô mai cà chua', 'pasta-pho-mai-ca-chua', 'Bước 1: Đun sôi nước trên lửa vừa, cho muối vào rồi cho mì vào luộc với một chút ít dầu ăn để không bị dính với nhau. Vớt mì ra (giữ lại khoảng 1/4 - 1/2 chén nước luộc mì), xả qua chút nước lạnh và để ráo nước. Cà chua bi rửa sạch, cắt đôi. Tỏi bóc vỏ, thái lát. <br>\r\nBước 2: Đun nóng chảo dầu, cho tỏi vào phi thơm rồi thả cà chua vào xào cho đến khi mềm, kế tiếp cho mì đã luộc và muối vào xào rồi tắt bếp. Chuẩn bị phần phô mai để bên cạnh. <br>\r\nBước 3: Cho phô mai vào phần mì, múc từng muỗng nước luộc mì còn nóng vào rồi trộn đều lại nữa là hoàn thành. Bạn chú ý không cho một lượt nước luộc mì vào mà là cho đến đâu, trộn đến đó, khi cho quá nhiều, mì sẽ bị sũng nước. <br>\r\nBước 4: Thưởng thức thôi nào. Vị thơm và béo của phô mai, cộng thêm mì Ý dẻo dai làm món ăn càng hấp dẫn, ngon miệng hơn. Chị em có thể đổi chút khẩu vị cho cà nhà với món này cho dễ ăn nha. <br>', 'pasta_pho_mai_ca_chua.jpg', 0, 0, 12, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(43, 'Phở xào bò', 'pho-xao-bo', 'Bước 1: Cho nước tương, giấm gạo, gừng băm, tỏi băm, tương ớt, dầu mè vào trong bát, khuấy đều rồi để riêng. Thịt bò sạch sạch, thái lát mỏng. Cho 1/2 bát hỗn hợp sốt ướp cùng thịt bò, 1/2 bát vẫn giữ nguyên. Bắc chảo lên bếp, cho dầu ăn vào đun nóng, thả thịt bò vào xào khoảng 1 phút. <br>\r\nBước 2: Thịt bò đã xào xong, bạn cho ra ngoài để riêng rồi thả hành tây vào xào trong khoảng 1 phút, kế đó, cho giá đỗ vào xào 30 giây nữa. Cho bánh phở vào xào. Thả phần thịt bò cùng 1/2 bát nước sốt trở lại, đảo đều cho nước sốt thấm vào bánh phở cùng rau củ, cho hành lá vào, đảo đều lần nữa rồi tắt bếp. <br>\r\nBước 3: Cho phở ra bát đĩa rồi thưởng thức. Cách chế biến này sẽ đem lại cho bạn một đĩa phở xào thơm ngon, thịt bò mềm ngọt cho bữa sáng gia đình thêm phần ngon miệng và hấp dẫn. <br>', 'pho_xao_bo.jpg', 0, 0, 15, '2019-01-01 16:01:19', '2019-01-01 16:01:19');
INSERT INTO `congthuc` (`id`, `TieuDe`, `TieuDeKhongDau`, `NoiDung`, `Hinh`, `NoiBat`, `SoLuotXem`, `idLoaiMon`, `created_at`, `updated_at`) VALUES
(44, 'Phở xào lạp xưởng tôm', 'pho-xao-lap-xuong-tom', 'Bước 1: Bánh phở khô cho vào tô nước ấm ngâm khoảng 30 - 45 phút cho nở mềm, sau đó vớt ra cho ráo nước. Có thể cắt thành khúc vừa ăn nếu phở dài quá nha. Giá, hẹ rửa thật sạch và để ráo nước, hẹ cắt khúc ngắn. hành lá xắt khúc xéo. Chả cá cắt lát. Tôm lột vỏ, lấy chỉ, bỏ đầu và rửa thật sạch. Trứng cho ra chén đánh tan. Lạp xưởng cắt lát xéo. Nước sốt: trộn đều 2 muỗng hắc xì dầu, 2 muỗng nước tương, 1 muỗng nước mắm, dầu hào, tiêu, đường trong chén nhỏ. <br>\r\nBước 2: Đun nóng chảo dầu, pho thơm tỏi, thả lạp xưởng vào chiên 20 giây cho chín. Sau đó cho tôm tươi cùng chả cá vào đảo đều thêm 20 giây nữa, rưới 1 muỗng rượu vào xào khoảng 15 giây. Cho bánh phở đã ngâm vào, xào cho đều lên. Rưới phần nước sốt đã chuẩn bị vào phở và đảo nhẹ tay để bánh phở không bị bể nát. <br>\r\nBước 3: Khi thấy tất cả đã thấm gia vị thì cho hẹ cắt khúc vào, trộn cho tất cả hòa vào nhau. Tạo một khoảng trống, đổ trứng vào trong chảo và khuấy trộn lên để trứng bám vào sợi phở. Sau cùng cho giá vào xào nhẹ tay vài phút cho giá chính là hoàn tành nha. Gắp phở xào ra dĩa và thưởng thức ngay khi còn nóng. <br>\r\nBước 4: Món phở lạp xưởng tôm tươi không chỉ ngon về hương vị đậm đà, sợi bánh phở mềm dai cùng lạp xưởng và các loại rau giá tạo độ ngon, không ngán đâu đấy. Nhanh tay lưu ngay công thức lại và làm ăn nhé. <br>', 'pho_xao_lap_xuong_tom.jpg', 0, 0, 15, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(45, 'Rau củ xào thập cẩm', 'rau-cu-xao-thap-cam', 'Bước 1: Đậu bắp rửa sạch, đem luộc 2 phút rồi vớt ra, thái lát nhỏ. Cà rốt tỉa hoa, cắt lát mỏng. Củ cây hoa lily tách lấy từng cánh nhỏ, rửa sạch. bắp hột luộc chín vớt ra để riêng. <br>\r\nBước 2: Đun nóng 2 muỗng canh dầu ăn, cho cà rốt vào xào lửa nhỏ vừa cho cà rốt chín mềm. Cho tiếp bắp hột, đậu bắp vào xào. Cuối cùng cho hoa lily vào xào. Nêm 1/3 muỗng cà phê muối, 1 muỗng canh nước tương, xào tiếp 2 phút, tắt bếp. <br>\r\nBước 3: Món rau củ xào thập cẩm chay hội tụ nhiều màu sắc nổi bật trông rất hấp dẫn. Thích hợp dùng cho những bữa cơm ngày chay của gia đình bạn. Món này còn thích hợp cho các thực đơn ăn kiêng của chị em nữa nhé! <br>', 'rau_cu_xao_thap_cam.jpg', 0, 0, 5, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(46, 'Rượu trái cây', 'ruou-trai-cay', 'Bước 1: Trái cây bạn mua về ngâm muối rửa thật sạch: 300gr dâu tây, 500gr chuối sứ chín, 500gr táo, 500gr cam vàng, 300gr sơ ri, 300gr chanh, 300gr thơm. Để trái cây thật ráo nước rồi cắt lát mỏng. Riêng chanh bạn nhớ gọt vỏ để rượu không bị đắng nhé. <br>\r\nBước 2: Hủ thủy tinh bạn rửa thật sạch bằng nước nóng để hết sạch vi khuẩn, để cho ráo nước rồi xếp lần lượt 1 lớp trái cây 1 lớp đường, cho đến khi hết trái cây. Lớp trái cây cuối cùng bạn rót 100ml rượu Vodka vào rồi mới phủ đường lên để trái cây không bị mốc. Cuối cùng bạn đậy hủ thật kín và để chỗ mát cho rượu lên men nhé. <br>\r\nBước 3: Rượu ngâm sau 2-3 tuần là có thể dùng được. Vị chua chua ngọt ngọt thơm lừng mùi trái cây sẽ là món rượu ngon và tốt cho sức khỏe. Uống 1 ly rượu trái cây mỗi ngày sau bữa ăn hay dùng để tiếp đãi bạn bè ngày Tết sẽ rất thú vị. <br>', 'ruou_trai_cay.jpg', 0, 0, 9, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(47, 'Sa tế cay thơm', 'sa-te-cay-thom', 'Bước 1: Ớt bột ngâm với nước nóng khoảng 20 phút cho nở. Ớt tươi chọn quả tươi cứng, sả rửa sạch để ráo. Các bạn băm hoặc xay nhỏ ớt và sả. <br>\r\nBước 2: Đặt chảo dầu lên bếp, do các nguyên liệu khá hút dầu nên Bếp dùng khoảng 300-400ml dầu ăn. Bật lửa đợi dầu nóng, các bạn cho hạt màu điều vào xào. Lửa vừa vừa nhé, để hạt ra màu từ từ. Không để dầu sôi, hạt sẽ bị cháy. <br>\r\nBước 3: Sau khi hạt ra hết màu, các bạn tắt bếp, lọc dầu qua rây, bỏ hạt màu điều đi. Dùng dầu vừa lọc phi thơm tỏi và hành tím. Tiếp tục cho sả băm vào xào, khi sả bốc mùi thơm cho tiếp ớt tươi và ớt bột khuấy đều. Nêm 2 muỗng cà phê muối, 2 muỗng cà phê đường, 2 muỗng cà phê nước mắm. Tiếp tục rim các nguyên liệu trên bếp khoảng 20 phút thì tắt bếp. <br>\r\nBước 4: Chờ sa tế nguội cho vào hũ thủy tinh sạch, cất dùng dần. Sa tế ớt cay thơm thường thấy trong các món bún nước hay hủ tiếu giúp món ăn thêm cay béo hấp dẫn. Ngoài ra, các món nướng cũng ướp chung sa tế để óc được màu đẹp và vị cay cay ngon miệng. <br>', 'sa_te_cay_thom.jpg', 0, 0, 11, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(48, 'Salad dưa leo', 'salad-dua-leo', 'Bước 1: Dưa leo rửa sạch, nạo vỏ. Cắt đôi quả dưa leo theo chiều dọc rồi nạo bỏ lõi. <br>\r\nBước 2: Sau đó, cắt dưa leo thành các miếng có kích cỡ khoảng 0.6cm. <br>\r\nBước 3: Cho dưa leo ra tô, rắc 1 muỗng canh muối và trộn đều. Sau đó cho dưa vào trong tủ lạnh khoảng 1 giờ. Sau đó, dùng tay bóp dưa leo cho ra bớt nước. <br>\r\nBước 4: Trong một tô vừa, trộn dưa leo với 3 muỗng canh giấm, 1 muỗng canh dầu mè, 1/2 muỗng canh đường. Thêm 3 muỗng canh nước tương và trộn đều. Sau đó, cho 1 muỗng canh tương ớt vào, đảo đều. <br>\r\nBước 5: Giờ chỉ việc thưởng thức salad dưa leo luôn hoặc để dành trong tủ lạnh một vài ngày. <br>', 'salad_dua_leo.jpg', 0, 0, 10, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(49, 'Salad Poké tôm', 'salad-poke-tom', 'Bước 1: Nấm bỏ gốc, rửa sạch và tách rời. Cà rốt bào sợi. Cả 2 đều xào với nước tương và đường tỉ lệ 2:1, thêm cả hành lá. Dưa leo gọt vỏ, bỏ hạt, cắt nhỏ. <br>\r\nBước 2: Luộc tôm, lột vỏ, cắt làm 3 miếng nhỏ và trộn với sốt Shoyou. Bưởi lột vỏ, bỏ hạt, bẻ thành từng miếng nhỏ. <br>\r\nBước 3: Xà lách bỏ gốc, cắt miếng vừa ăn. Cà chua bi thì rửa bỏ cuống rồi cắt đôi. Cho xà lách vào tô, xịt sốt mè rang lên. Rồi cho các toppings xếp xung quanh. <br>\r\nBước 4: Cuối cùng là protein tôm ở giữa. Mình ăn kèm với sốt mè và Mayo cay. Shoyou thì có vị chua (nhưng không chua bằng Ponyou) thích hợp để trộn tôm hoặc cá. Ăn kèm salad sốt mè là hợp nhất, để thêm kích thích thị giác (xíu cay cay) thì mình thêm Mayo cay nè. <br>\r\n', 'salad_poke_tom.jpg', 0, 0, 10, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(50, 'Salad trái cây', 'salad-trai-cay', 'Bước 1: Dùng một chiếc bát sạch, bạn cho mật ong và nước chanh vào rồi dùng đũa khuấy đều. Rửa sạch nho, dâu tây rồi dùng dao cắt nhỏ. Sau đó, bạn cho hết vào một chiếc tô lớn. <br>\r\nBước 2: Bỏ thêm táo và chuối đã cắt nhỏ vào. Cho thêm quả việt quất vào cùng. Tiếp theo, đổ hỗn hợp nước mật ong chanh vào bát hoa quả. Trộn đều hỗn hợp nhẹ nhàng và để trong 6 tiếng ở tủ lạnh để hỗn hợp ngấm. <br>\r\nBước 3: Salad trái cây chóng ngán cho ngày Tết với cách làm đơn giản, món salad trái cây với đầy đủ màu sắc và hương vị này hứa hẹn mang đến nhiều may mắn chả nhà trong những ngày đầu năm. <br>', 'salad_trai_cay.jpg', 0, 0, 10, '2019-01-01 16:01:19', '2019-01-01 16:01:19'),
(51, 'Sinh tố táo', 'sinh-to-tao', 'Bước 1: Táo gọt vỏ cắt nhỏ cho vào 1 tô nước có 1 ít chanh trong đó nhé (như vậy táo sẽ không bị đen). <br>\r\nBước 2: Cho táo vào máy xay sinh tố, sau đó cho vào 3 muỗng canh sữa đặc (bạn thích ăn đường thì cho vào nhé, Hằng không thích nên sẽ không cho đường), sau đó cho đá vào. Rồi xay cho mịn ra. <br>\r\nBước 3: Món ăn đã hoàn thành, quá đơn giản phải không các bạn. Chúc các bạn thành công <br>', 'sinh_to_tao.jpg', 0, 0, 9, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(52, 'Sốt bơ trứng', 'sot-bo-trung', 'Bước 1: Trứng gà mua về, bạn nên chọn trứng gà ta sẽ có hương vị thơm hơn so với trứng gà công nghiệp nhé. Đập trứng, dùng đũa hoặc nĩa đánh đều theo chiều kim đồng hồ, cho lòng trắng và lòng đỏ hòa quyện. <br>\r\nBước 2: Đun sôi nước, cho bơ vào chén, đặt trong nước đã sôi 5 phút, đến khi bơ tan hoàn toàn thì khuấy nhẹ bơ. <br>\r\nBước 3: Đặt trứng đã đánh đều vào nồi nước đã đun sôi, sử dụng hơi nóng của nước còn lại liên tục khuấy đều trứng, từ từ thêm bơ, đường, muối vào cùng với trứng. Khuấy đều cho đến khi trứng bơ hòa quyện thành sốt sệt. <br>\r\nBước 4: Cuối cùng thêm vào trứng nước cốt chanh nhằm cân bằng hương vị, tránh thêm quá nhiều nước cốt chanh sẽ làm trứng và bơ tách lỏng khi nguội không còn ngon nhé. <br>\r\nBước 5: Vậy là chúng ta đã có ngay chén sốt bơ trứng béo bùi, thơm lừng, vừa có vị mặn, ngọt, vừa có chút vị chua của chanh khi chấm với rau củ luộc cùng hoặc trộn salad sẽ rất ngon đấy. <br>', 'sot_bo_trung.jpg', 0, 0, 11, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(53, 'Sốt cà chua', 'sot-ca-chua', 'Bước 1: Hành tây băm nhỏ hoặc thái hạt lựu. Cà chua rửa sạch, bỏ cuống, khứa chéo đầu. <br>\r\nBước 2: Bắc nồi lên bếp, đổ nước xâm xấp với cà chua, luộc chín cà chua rồi bóc lớp vỏ đi. Đặt chảo lên bếp, đun nóng dầu ăn rồi cho tỏi vào phi, tiếp đến cho hành tây, gừng, tiêu, mù tạt và muối vào, đun 10 phút cho mềm. <br>\r\nBước 3: Cho cà chua đã bóc vỏ vào nồi hành tây ban đầu. Tiếp đến cho đường, dấm và tiếp tục nấu. Dùng thìa nhẹ nhàng nghiền cà chua nhuyễn ra. đảo đều tay trong 10 phút đến khi hỗn hợp đặc sánh lại <br>\r\nBước 4: Tắt bếp để nước sốt nguội rồi cho vào máy xay mịn ra. Rót phần sốt vào lọ, đậy kín bảo quản trong tủ lạnh, bảo quản lạnh có thể dùng được trong vòng 1 tháng liền. <br>', 'sot_ca_chua.jpg', 0, 0, 11, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(54, 'Sốt chấm xoài', 'sot-cham-xoai', 'Bước 1: Tép khô đem ngâm với nước ấm cho nở, sau đó gạn khéo để tép sạch cát và rửa tép vài lần nước cho sạch bụi bẩn, vớt ra vắt sạch nước để riêng. Hành, tỏi, ớt rửa sạch, băm nhỏ. Cho chút dầu ăn vào chảo, đợi dầu sôi cho hành tỏi vào phi vàng và thơm nhưng đừng để cháy quá sẽ bị đắng, tiếp đến là cho ớt băm. <br>\r\nBước 2: Trút hết phần tép khô vào đảo cho vàng, dậy mùi thơm là được. Cuối cùng cho đường, nước mắm, nước lọc, khuấy cho đều, hạ lửa trung bình, hỗn hợp sôi nêm nếm gia vị cho vừa miệng. Có thể cho thêm chút bột canh, bột nêm hoặc mỳ chính vào. Đổ hết phần ớt bột khô vào. Đun nhỏ lửa cho hỗn hợp keo lại, hơi sền sệt là được, gần như cách mình làm kho quẹt đó. <br>\r\nBước 3: Vậy là xong rồi đó. Những miếng xoài, trái cây chua ngon lành, thơm phức chấm với sốt mặn mặn, ngọt ngọt, cay cay không chỉ hấp dẫn chị em mà còn là món “lai rai” đắt khách. Thử làm và bạn sẽ nghiện món sốt chấm này cho xem. <br>', 'sot_cham_xoai.png', 0, 0, 11, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(55, 'Sốt chanh bơ', 'sot-chanh-bo', 'Bước 1: Chanh vắt lấy nước cốt, bỏ hạt nếu có. Trứng gà khéo léo tách lấy lòng đỏ. Lòng đỏ trứng cho vào tô đánh bông lên cùng với đường, vỏ chanh và nước cốt chanh. <br>\r\nBước 2: Đun nồi hấp cách thủy. Cho hỗn hợp đã đánh tan ở trên đặt vào nồi khuấy đều. Khi đường tan thì cho trứng vào tiếp tục khuấy đều cho hỗn hợp không bị vón cục. Nấu cho đến khi hỗn hợp đặc sệt lại giống như sữa chua hoặc kem chua vậy. <br>\r\nBước 3: Đổ hỗn hợp vào lọ và cất trữ trong tủ lạnh, dùng dần từ 7-10 ngày nhé. Sốt chanh bơ có thể ăn cùng bánh mì hay làm nhân bánh ngọt, crepe, tart hay pancakes, hay là ăn với scones. Cũng làm thử món mứt hấp dẫn cho mỗi buổi sáng nhé! <br>', 'sot_chanh_bo.jpg', 0, 0, 11, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(56, 'Spaghetti rượu vang đỏ', 'spaghetti-ruou-vang-do', 'Bước 1: Cho rượu vang đỏ, muối và nước vào nồi, bắc lên bếp đun sôi. Thả mì Ý vào và giảm lửa, đun cho đến khi rượu được hấp thụ vào sợi mì. Tùy theo loại mì bạn đang sử dụng mà thời gian sẽ khác nhau, nhưng trung bình là khoảng 10-15 phút. Giữ lại khoảng 1 chén nước luộc mì trước khi xả ráo. <br>\r\nBước 2: Hạt thông rang cho đến khi vàng trong một cái chảo. Đun nóng 1 muỗng canh bơ trong chảo, cho tỏi băm vào phi thơm, cho phần mì rượu vang vào đảo đều. Bạn có thể cho thêm 1 ít nước luộc mì nếu muốn mì sệt hơn. Tắt lửa, cho phần bơ còn lại, hạt thông, nước cốt chanh, lá húng quế băm, phô mai vào. <br>\r\nBước 3: Sợi mì đỏ tím tuyệt đẹp đắm mình trong rượu vang sánh đậm đã và đang chinh phục khẩu vị rất nhiều thực khách ở mọi lứa tuổi. Cùng trổ tài đãi cả nhà với món mì trong cuối tuần này nhé! <br>', 'spaghetti_ruou_vang_do.jpg', 0, 0, 12, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(57, 'Sữa chua phô mai', 'sua-chua-pho-mai', 'Bước 1: Đun nóng 500ml sữa tươi với 80gr sữa đặc và 2 viên phô mai tam giác. <br>\r\nBước 2: Khuấy đều cho tan hết phô mai rồi lượt qua rây cho hết cợn. <br>\r\nBước 3: Để hỗn hợp sữa nguội bớt khoảng 40 độ C rồi mới thêm 100gr sữa chua cái đã mịn vào hủ. Khuấy nhẹ tay cho hỗn hợp hòa quyện. <br>\r\nBước 4: Rót sữa chua vào hủ thủy tinh và đậy nắp kín. Đặt nhẹ nhàng từng hủ vào nồi, sau đó rót nước nóng 70-80 độ đến 2/3 hủ. Cuối cùng phủ khăn lên trên và đậy nắp lại. Ủ sữa chua 6-8 tiếng. Các bạn nhớ thường xuyên thay nước ủ khi nước nguội nhé (khoảng 2-3 tiếng) . <br>\r\nBước 5: Sau khi ủ xong sữa chua đặc không bị tách nước hoặc quá lỏng là thành công. Sữa chua ủ xong là bạn cho vào ngăn mát tủ lạnh tầm 2-3 tiếng là chúng ta có thể thưởng thức. Sữa chua phô mai có thể kết hợp ăn chung với các loại trái cây cũng rất ngon và tốt cho sức khỏe. <br>', 'sua_chua_pho_mai.jpg', 0, 0, 2, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(58, 'Sữa lắc chocolate nước cốt dừa', 'sua-lac-chocolate-nuoc-cot-dua', 'Bước 1: Kem là nguyên liệu chính của món sữa lắc, vì thế nếu thực hiện loại thực uống này, bạn hãy chọn loại kem có chất lượng tốt nha. Chuẩn bị máy xay sinh tố, cho kem chocolate, nước cốt dừa, bột cacao, chocolate vào máy xay sinh tố. Bật công tắc xay nhuyễn hỗn hợp. <br>\r\nBước 2: Chuẩn bị ly thủy tinh đã làm lạnh sẵn, rót hỗn hợp ra ly. Bạn có thể trang trí thêm 1 ít kem viên như kem dừa, kem vani, kem sữa tươi cũng rất hợp, rắc thêm 1 ít dừa nạo nướng cho thơm nữa nè. <br>\r\nBước 3: Vậy là chúng ta đã hoàn thành thức uống thơm ngon, ngọt béo này rồi. Thật tuyệt vì bạn có thể cảm nhận được tất cả hương vị trong một ly sữa vừa giàu năng lượng lại đơn giản, dễ làm. <br>', 'sua_lac_chocolate_nuoc_cot_dua.jpg', 0, 0, 9, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(59, 'Sườn xào chua ngọt', 'suon-xao-chua-ngot', 'Bước 1: Sườn heo chặt khúc, rửa sạch với nước, cho vào nồi nước sôi chần sơ qua 3 phút. <br>\r\nBước 2: Vớt sườn heo ra, ướp với hành tím băm, 1 muỗng cà phê hạt nêm, 1/2 muỗng canh bột năng trong tô, cho vào chảo với 2 muỗng canh dầu ăn, chiên sơ qua. <br>\r\nBước 3: Phi thơm tỏi băm với 2 muỗng canh dầu ăn còn lại, cho sườn heo, 1 muỗng canh đường trắng, 1 muỗng canh nước mắm, 1 muỗng canh nước cốt chanh, 1 muỗng canh sa tế vào, đảo đều 3 phút. <br>\r\nBước 4: Tắt bếp, cho món ăn ra đĩa và dùng ngay. Sườn mềm, thấm đậm gia vị ăn cực ngon. <br>\r\n', 'suon_xao_chua_ngot.jpg', 0, 0, 5, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(60, 'Thịt nghêu xào cay', 'thit-ngheu-xao-cay', 'Bước 1: Thịt nghêu đem rã đông nếu có, giũ thật ráo nước. Nếu không có thit nghêu sẵn thì bạn tiến hành luộc sơ nghêu cho vừa há miệng thì dùng dao cắt lấy thịt nghêu, rửa sạch cát nhé! Hành lá và hẹ rửa sạch, cắt khúc ngắn khoảng 2cm. <br>\r\nBước 2: Đun nóng 1 muỗng canh dầu ăn, cho 2 muỗng canh sốt ớt đậu cay vào đảo đều cho dậy mùi. Cho thịt nghêu vào xào đều tay. Nêm 1/4 muỗng cà phê muối, 1 muỗng cà phê đường. Xào cho nghêu ngấm gia vị thì cho ngò rí và hẹ vào đảo đều, tắt bếp. <br>\r\nBước 3: Cả nhà mình đều rất thích ăn món thịt nghêu xào cay này. Thịt nghêu dai dai rất ngon cơm. Ngoài ra vị cay nồng của món xào giúp ấm bụng cho những bữa cơm chiều mùa đồng nữa nhé! <br>', 'thit_ngheu_xao_cay.jpg', 0, 0, 5, '2019-01-01 16:50:11', '2019-01-01 16:50:11'),
(61, 'Tokbokki Hàn Quốc', 'tokbokki-han-quoc', 'Bước 1: Sơ chế các nguyên liệu đã chuẩn bị. Bắp cải và hành boa rô rửa sạch cắt miếng vừa ăn. Tokbokki luộc sơ sau đó ngâm qua nước lạnh, vớt lên để ráo. <br>\r\nBước 2: Cho chảo lên bếp thêm chút dầu ăn xào sơ hành boa rô sau đó đổ bắp cải vào xào chung. Bắp cải vừa chín tới đổ bịch sốt tokbokki đã chuẩn bị vào tiếp đến là bánh gạo đã luộc sẵn. Đảo theo vòng tròn để bánh gạo không bị nát. Nước sốt đặc sánh lại, bánh gạo mềm thì tắt bếp. <br>\r\nBước 3: Đổ bánh gạo ra dĩa rắc thêm mè và thưởng thức. Bánh gạo mềm dai quyện với nước sốt cay nồng, đậm đà kèm thêm bắp cải giòn ngọt tạo nên một món ăn vô cùng ngon miệng. <br>', 'tokbokki_han_quoc.jpg', 0, 0, 2, '2019-01-01 17:01:23', '2019-01-01 17:01:23'),
(62, 'Ức gà chiên áp chảo', 'uc-ga-chien-ap-chao', 'Bước 1: Thịt ức gà cắt bỏ phần da và mỡ thừa, rửa sạch. Dùng khăn thấm khô miếng thịt rồi dùng dao khứa vài đường song song lên thịt gà để dễ ngấm gia vị. Cho thịt gà vào tô, thêm 20g gia vị ướp món nướng, 20ml nước, trộn đều, xoa bóp cho thịt áo đều. Ướp trong ngăn mát tủ lạnh khoảng 2 giờ. <br>\r\nBước 2: Thịt gà sau khi ướp thấm khô nước ướp. Đun nóng nhiều dầu ăn trong chảo, cho thịt ức gà vào chiên áp chảo với lửa nhỏ vừa. Thường xuyên trở mặt thịt cho thịt chiên chín đều là được nhé! <br>\r\nBước 3: Món thịt ức gà chiên áp chảo thơm ngon này mình chẳng cần phải đắn đo gì khi tổng hợp nguyên liệu ướp. Chỉ cần 1 gói gia vị ướp món nước thế là được. Món ức gà chiên chảo đáy phẳng giúp nhiệt được lan đều khắp miếng thịt hơn. <br>', 'uc_ga_chien_ap_chao.jpg', 0, 0, 13, '2019-01-01 17:01:23', '2019-01-01 17:01:23'),
(63, 'Ức gà chiên giòn', 'uc-ga-chien-gion', 'Bước 1: Thịt ức gà rửa thật sạch, để ráo rồi cắt thành từng miếng dài vừa. Cho thịt gà vào tô ướp với 9ml rượu nấu ăn, 10g hành lá băm, 1 muỗng gừng băm, 3g tiêu, 7g muối, 10ml nước tương và để 15 phút cho thấm gia vị. Đổ 30g bột mì ra dĩa, thịt sau khi ướp lăn qua một lớp bột mì. Trứng đập ra tô, đánh tan. Thịt sau khi đã lăn một lớp bột mì thì nhúng vào tô trứng cho phủ đều miếng thịt. <br>\r\nBước 2: Rong biển khô cho ra dĩa sâu lòng, đổ 30g bột chiên xù vào, trộn đều lên. Lấy thịt đã nhúng trứng cho vào dĩa bột chiên xù, lăn cho bột cùng rong biển bám đều lên miếng thịt. Đun nóng dầu ăn, thả thịt gà vào chiên chín, vàng ươm và giòn tất cả các mặt thì gắp ra dĩa có lót giấy thấm dầu là xong rồi đó. Thịt gà chiên giòn ăn ngon nhất là khi chấm cùng tương ớt đó. <br>\r\nBước 3: Vậy là chỉ cần một chút một chút biến tấu trong khâu trộn bột khi kết hợp thêm rong biển đã giúp món Ức gà chiên giòn rụm cực kì hấp dẫn và ngon lành đấy. Cùng lưu công thức và thử làm nha. <br>', 'uc_ga_chien_gion.jpg', 0, 0, 13, '2019-01-01 17:01:23', '2019-01-01 17:01:23'),
(64, 'Xúc xích cuộn sandwich chiên xù', 'xuc-xich-cuon-sandwich-chien-xu', 'Bước 1: Chuẩn bị nguyên liệu. Bánh mì cắt vỏ chỉ lấy phần nhân bánh mì. Xiên xúc xích vào que. Đập 3 trứng vào dĩa để làm chất kết dính khi cuộn xong, chiên không bị vỡ. <br>\r\nBước 2: Cuốn như hướng dẫn ở hình dưới. Cho bánh mì trên dĩa, đặt xúc xích từ ngoài cuốn vào, làm lần lượt với xúc xích còn lại. Nhúng bánh mì cuộn xúc xích qua lớp trứng, cuối cùng nhúng qua lớp bột chiên xù. <br>\r\nBước 3: Cho chảo lên bếp, cho dầu ăn, chờ dầu nóng, cho lần lượt xúc xích vào chiên vàng rồi gắp ra dĩa có lót giấy thấm dầu ăn. Cho tất cả vào dĩa, cho vào microwave quay 5 phút cho ráo dầu, ăn sẽ không bị ngáy. <br>\r\nBước 4: Tèn ten ten, thành phẩm những que xúc xích bánh mì chiên vàng ươm siêu hấp dẫn luôn, ăn kèm với sốt hoặc đơn giản là tương ớt thôi cũng xuất sắc nhé. Chúc cả nhà thành công! <br>', 'xuc_xich_cuon_sandwich_chien_xu.jpg', 0, 0, 2, '2019-01-01 17:01:23', '2019-01-01 17:01:23');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `loaimon`
--

CREATE TABLE `loaimon` (
  `id` int(10) UNSIGNED NOT NULL,
  `Ten` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `TenKhongDau` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `loaimon`
--

INSERT INTO `loaimon` (`id`, `Ten`, `TenKhongDau`, `created_at`, `updated_at`) VALUES
(1, 'Ăn sáng', 'An-sang', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(2, 'Ăn vặt', 'An-vat', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(3, 'Khai vị', 'Khai-vi', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(4, 'Món chay', 'Mon-chay', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(5, 'Món chính', 'Mon-chinh', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(6, 'Nhanh - Dễ', 'Nhanh-de', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(7, 'Bánh', 'Banh', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(8, 'Healthy', 'Healthy', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(9, 'Thức uống', 'Thuc-uong', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(10, 'Salad', 'Salad', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(11, 'Nước chấm', 'Nuoc-cham', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(12, 'Pasta - Spaghetti', 'Pasta-spaghetti', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(13, 'Gà', 'Ga', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(14, 'Snacks', 'Snacks', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(15, 'Bún - Mì - Phở', 'Bun-mi-pho', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(16, 'Lẩu', 'Lau', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `users`
--

CREATE TABLE `users` (
  `id` int(10) UNSIGNED NOT NULL,
  `firstname` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `access_level` varchar(16) COLLATE utf8_unicode_ci NOT NULL,
  `access_code` text COLLATE utf8_unicode_ci NOT NULL,
  `status` int(11) NOT NULL COMMENT '0=pending,1=confirmed',
  `created` datetime NOT NULL,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='admin and customer users';

--
-- Đang đổ dữ liệu cho bảng `users`
--

INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `contact_number`, `address`, `password`, `access_level`, `access_code`, `status`, `created`, `modified`) VALUES
(1, 'Darwin', 'Dalisay', 'darwin@example.com', '9331868359', 'Blk 24 A Lot 6 Ph 3\r\nPeace Village, San Luis', '$2y$10$tLq9lTKDUt7EyTFhxL0QHuen/BgO9YQzFYTUyH50kJXLJ.ISO3HAO', 'Customer', 'ILXFBdMAbHVrJswNDnm231cziO8FZomn', 1, '2014-10-29 17:31:09', '2018-12-23 14:12:07'),
(2, 'Kobe Bro', 'Bryant', 'kobe@gmail.com', '09898787674', 'Los Angeles, California', '$2y$10$fmanyjJxNfJ8O3p9jjUixu6EOHkGZrThtcd..TeNz2g.XZyCIuVpm', 'Customer', '', 1, '2015-03-26 11:28:01', '2018-12-23 14:12:31'),
(3, 'Mike', 'Dalisay', 'mike@example.com', '0999999999', 'Blk. 24 A, Lot 6, Ph. 3, Peace Village', '$2y$10$AUBptrm9sQF696zr8Hv31On3x4wqnTihdCLocZmGLbiDvyLpyokL.', 'Admin', '', 1, '0000-00-00 00:00:00', '2018-12-23 14:12:39'),
(4, 'Charlon', 'Ignacio', 'charlon@gmail.com', '09876543345', 'Tandang Sora, QC', '$2y$10$Fj6O1tPYI6UZRzJ9BNfFJuhURN9DnK5fQGHEsfol5LXRu.tCYYggu', 'Customer', '', 1, '2015-03-24 08:06:57', '2018-12-23 14:12:46'),
(5, 'Lauro', 'Abogne', 'lauro@eacomm.com', '08888888', 'Pasig City', '$2y$10$it4i11kRKrB19FfpPRWsRO5qtgrgajL7NnxOq180MsIhCKhAmSdDa', 'Customer', '', 1, '0000-00-00 00:00:00', '2018-12-23 14:12:20'),
(6, 'Marisol Jane', 'Dalisay', 'mariz@gmail.com', '09998765432', 'Blk. 24 A, Lot 6, Ph. 3, Peace Village', 'mariz', 'Customer', '', 1, '2015-02-25 09:35:52', '2018-12-23 14:12:55'),
(7, 'Marykris', 'De Leon', 'marykrisdarell.deleon@gmail.com', '09194444444', 'Project 4, QC', '$2y$10$uUy7D5qmvaRYttLCx9wnU.WOD3/8URgOX7OBXHPpWyTDjU4ZteSEm', 'Customer', '', 1, '2015-02-27 14:28:46', '2018-12-23 14:13:06'),
(8, 'Merlin', 'Duckerberg', 'merlin@gmail.com', '09991112333', 'Project 2, Quezon City', '$2y$10$VHY58eALB1QyYsP71RHD1ewmVxZZp.wLuhejyQrufvdy041arx1Kq', 'Admin', '', 1, '2015-03-18 06:45:28', '2018-12-23 14:13:22'),
(9, 'Tim', 'Duncan', 'tim@example.com', '9999999', 'San Antonio, Texas, USA', '$2y$10$9OSKHLhiDdBkJTmd3VLnQeNPCtyH1IvZmcHrz4khBMHdxc8PLX5G6', 'Customer', '0X4JwsRmdif8UyyIHSOUjhZz9tva3Czj', 1, '2016-05-26 01:25:59', '2018-12-23 14:13:29'),
(10, 'Tony', 'Parker', 'tony@example.com', '8888888', 'Blk 24 A Lot 6 Ph 3\r\nPeace Village, San Luis', '$2y$10$lBJfvLyl/X5PieaztTYADOxOQeZJCqETayF.O9ld17z3hcKSJwZae', 'Customer', 'THM3xkZzXeza5ISoTyPKl6oLpVa88tYl', 1, '2016-05-26 01:29:01', '2018-12-23 14:13:39'),
(12, 'Äá»©c TÃ¢m', 'Nguyá»…n', 'bigteddy198@gmail.com', '123456789', 'HÃ  Ná»™i', '$2y$10$deQggpxaFDzLCSZ6eTYwjeliJbvPF6nFuvxZtLrsg6L50E2/A88GC', 'Customer', 'BCxhJshaymHaJCfxquq85hpsK9RjL8Hu', 1, '2019-01-01 05:27:44', '2019-01-01 04:27:44'),
(13, 'HoÃ ng', 'Äáº·ng', 'vipboytk98@gmail.com', '123456789', 'HÃ  Ná»™i', '$2y$10$HQViF/56F4UKo4sHk2HDMu7NojpkIZ9hAzaD8gbUgz3wAzR8t9M6.', 'Customer', 'cEHlMMFl39uRS6wm65Y5liJlFJdKOalD', 1, '2019-01-03 14:40:43', '2019-01-03 13:44:22');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `comment`
--
ALTER TABLE `comment`
  ADD PRIMARY KEY (`id`),
  ADD KEY `cmt_fk1` (`idUser`),
  ADD KEY `cmt_fk2` (`idCongThuc`);

--
-- Chỉ mục cho bảng `congthuc`
--
ALTER TABLE `congthuc`
  ADD PRIMARY KEY (`id`),
  ADD KEY `ct_fk` (`idLoaiMon`);

--
-- Chỉ mục cho bảng `loaimon`
--
ALTER TABLE `loaimon`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `comment`
--
ALTER TABLE `comment`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `congthuc`
--
ALTER TABLE `congthuc`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=65;

--
-- AUTO_INCREMENT cho bảng `loaimon`
--
ALTER TABLE `loaimon`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT cho bảng `users`
--
ALTER TABLE `users`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `comment`
--
ALTER TABLE `comment`
  ADD CONSTRAINT `cmt_fk1` FOREIGN KEY (`idUser`) REFERENCES `users` (`id`),
  ADD CONSTRAINT `cmt_fk2` FOREIGN KEY (`idCongThuc`) REFERENCES `congthuc` (`id`);

--
-- Các ràng buộc cho bảng `congthuc`
--
ALTER TABLE `congthuc`
  ADD CONSTRAINT `ct_fk` FOREIGN KEY (`idLoaiMon`) REFERENCES `loaimon` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
